### ISSUE TITLE
Request for a Cortex Analyzer for Recorded Future

### ISSUE THREAD

**Issue by mjrodriguez42** [TheHive-Project/Cortex-Analyzers#102]
Request for a Cortex Analyzer for Recorded Future

### Request Type
Analyzer / Feature

### Description
I would like to request an analyzer for API access to Recorded Future for observable enrichment.

**Comment by mjrodriguez42** [comment]
Recorded Future will often provide a temp API key for testing purposes. If someone chooses to follow up on this request, I may be able to facilitate getting an API key to use.

**Comment by 3c7** [comment]
Would like to help.

**Comment by saadkadhi** [comment]
Thanks @3c7 for offering a helping hand. @mjrodriguez42 can you please facilitate getting an API key for @3c7 and possibly for us as well please so we can test his analyzer once produced?

**Comment by 3c7** [comment]
Contacted RF support in order to get a trial API key.

**Comment by 3c7** [comment]
Still no answer from Recorded Future, requested status update.

**Comment by 3c7** [comment]
Recorded Future told me today that they don't provide trial access to their service.

**Comment by 3c7** [comment]
Thank you @jojoob.
