### ISSUE TITLE
[Bug] Ldap_Query_2_0 Cortex Analyzer uid_search_field is missing Error

### ISSUE THREAD

**Issue by psyopm** [TheHive-Project/Cortex-Analyzers#1030]
**Describe the bug**
In the python file ldapQuery.py the `uid_search_field` is wrongly defined as `search_field`, which causes the Analyzer to run into the Exception **"uid_search_field is missing"**.

**To Reproduce**
1. Configure the Analyzer under the Cortex Analyzer Config.
2. Enable the Ldap_Query_2_0 Analyzer.
3. Run a new Analysis wit the Ldap_Query_2_0 Analyzer.

**Expected behavior**
The Analyzer should start the Analysis and request the defined attributes in the Cortex Analyzer Config to harvest the relevant LDAP information for the username/e-mail address provided as input. 

**Complementary information**
Cortex Analyzer Ldap_Query_2_0 Error message if a new Analysis is started:
![image](https://user-images.githubusercontent.com/60820232/131250708-bbc51068-10d3-48a5-a3f4-ddbe4aa9dae9.png)
 

**Work environment**
- Cortex version: 3.1.1-1
 - Cortex Analyzer/Responder name: Ldap_Query_2_0
- Cortex Analyzer/Responder version: 2.0

**Possible solutions**
In the python file ldapQuery.py Line 22 we need following 

**From:**
```python
"config.search_field", None, "uid_search_field is missing"
```

**To:**
```python
"config.uid_search_field", None, "uid_search_field is missing"
```

**Comment by psyopm** [comment]
Added Link to Pull Request #1031

**Comment by piotr3439** [comment]
Hi
Will the cortexneurons/ldap_query: 2 image be updated?
