### ISSUE TITLE
[Bug]  Elasticsearch_Analysis_1_0  docker Permission denied

### ISSUE THREAD

**Issue by frack113** [TheHive-Project/Cortex-Analyzers#1089]
**Describe the bug**
I have install [thehive4-cortex3-misp-shuffle template](https://github.com/TheHive-Project/Docker-Templates/tree/main/docker/thehive4-cortex3-misp-shuffle) on a ubuntu 20.04
All is green Thehive-Cortex-Misp so I add the analyzer: Elasticsearch_Analysis_1_0 
The job fail with `/job: 1: Elasticsearch/elk.py: Permission denied`

**To Reproduce**
Install from [thehive4-cortex3-misp-shuffle template](https://github.com/TheHive-Project/Docker-Templates/tree/main/docker/thehive4-cortex3-misp-shuffle)
Enable elasticsearch_analysis
Run analyzer with a IP test 

**Expected behavior**
Run a query to the other VM with a ELK running

**Complementary information**

In a terminal:  
```
sudo docker run -ti  cortexneurons/elasticsearch_analysis:1 
/bin/sh: 1: Elasticsearch/elk.py: Permission denied

sudo docker run -ti --entrypoint sh cortexneurons/elasticsearch_analysis:1 
ls result
drwxr-xr-x 2 root root 4096 Dec  1 00:02 Elasticsearch
-rw-r--r-- 1 root root 16490 Nov 30 23:20 elk.py
```

**Work environment**
 - Client OS:  Ubuntu 20.04.4 LTS
- Server OS: Docker version 20.10.14, build a224086 /docker-compose version 1.29.2, build 5becea4c
 - Browse type and version: Firefox 98.0.2 (64 bits)
- Cortex version:
  Cortex 3.1.4-1
  Elastic4Play 1.13.3
  Play 2.8.3
  Elastic4s 7.9.1
  ElasticSearch client 7.9.1
- Cortex Analyzer/Responder name: elasticsearch_analysis
- Cortex Analyzer/Responder version: 1 /docker

**Possible solutions**

**Additional context**

**Comment by V1D1AN** [comment]
I have the same problem

**Comment by jeromeleonard** [comment]
see #1106

**Comment by scott7rj** [comment]
same problem here, running cortex 3.1.7-1
