### ISSUE TITLE
Hybrid Analysis Analyzer not working anymore

### ISSUE THREAD

**Issue by X0x1RG9f** [TheHive-Project/Cortex-Analyzers#1090]
When trying to use Hybrid Analysis Cortex Analyser, analysis fail. I suppose this is because the old v1 API is not supported any more due to v2 migration.

Also tried in addition with VxAPI (which is working with HA API V2), but I'm not succeeding to interface it with Cortex. 

Is there another way to make Cortex work with HA API v2 ?

Thanks !
Ludo

**Comment by joeslazaro-cdw** [comment]
Someone motivated would have to edit the HybridAnalysis/HybridAnalysis_analyzer.py file to work with the new API and then submit a pull request with the changes. The v2 API is documented at https://www.hybrid-analysis.com/docs/api/v2.

It's not too difficult if you have some skill with Python.

**Comment by X0x1RG9f** [comment]
@joeslazaro-cdw implementation done here : https://github.com/TheHive-Project/Cortex-Analyzers/pull/1117

Waiting for PR to be reviewed but now has it working on my side.

**Comment by louismaxx** [comment]
Bumping the issue has its really useful ! 
Thank you @X0x1RG9f

**Comment by RVO25** [comment]
@X0x1RG9f The implementation as described in ticket #1117 is done. However the docker image (https://download.thehive-project.org/analyzers.json) doesn't seem to be updated yet. 
![afbeelding](https://github.com/TheHive-Project/Cortex-Analyzers/assets/154515086/5fc4ec73-efd0-4d12-b269-fb27717bad8b)

**Comment by nusantara-self** [comment]
Hello,

Issue addressed & fixed in PR #1117
