### ISSUE TITLE
[Bug] Docker image CIRCLHashlookup built without the execute bit on the python script

### ISSUE THREAD

**Issue by Andraaada** [TheHive-Project/Cortex-Analyzers#1101]
**Getting the following error when using the analyzer CIRCLHashlookup_1_0 on Cortex**

```
{
  "errorMessage": "/job: 1: CIRCLHashlookup/circlhashlookup_analyzer.py: Permission denied\n",
  "input": null,
  "success": false
}
```

After checking the docker image files on disk:

The entrypoint is not executable (no execute bit on the python script)

            "Entrypoint": [
                "/bin/sh",
                "-c",
                "CIRCLHashlookup/circlhashlookup_analyzer.py"
            ]

 **-rw-r--r--** 1 root root 1618 Oct 31  2021 /worker/CIRCLHashlookup/circlhashlookup_analyzer.py

**Possible solutions**
Rebuild the docker image, by setting the execute bit on the python script.

**Comment by jeromeleonard** [comment]
see #1106
