### ISSUE TITLE
Manalyze analyzer

### ISSUE THREAD

**Issue by lctrcl** [TheHive-Project/Cortex-Analyzers#116]
### Request Type
Analyzer

### Work Environment
N/A

### Description
Create analyzer for [Manalyze](https://github.com/JusticeRage/Manalyze), static analyzer for PE executables.

I created initial analyzer for Manalyze, using this quite a lot for quick malware triage. Feel free to try it out, it has very basic report template because my angular and html skills are not good. Requires docker. 

[https://github.com/lctrcl/cortex-analyzers](https://github.com/lctrcl/cortex-analyzers)

**Comment by saadkadhi** [comment]
@lctrcl wouldn't it be possible to remove the docker requirement?

**Comment by lctrcl** [comment]
@saadkadhi I certainly can, and it would require compile Manalyze from sources. But I also would like to keep docker option, as it's quite easy to deploy without managing additional requirements (except for having docker).
Should I create this as separate analyzers?

**Comment by saadkadhi** [comment]
Thanks for your reply. Stay put. We'll look at the code and let you know if we can stay like this or not? At any rate, thanks for your contribution!

**Comment by JusticeRage** [comment]
Hi! I'm Manalyze's original developer. Is there something I can do to help this happen? I would love to see the tool available in The Hive.

**Comment by saadkadhi** [comment]
Ping @3c7

**Comment by 3c7** [comment]
The analyzer provided by @lctrcl looks fine. I'd prefer to let the user choose if using docker or the native binary. If using docker, I need to check if it works with the containerized analyzers in #171. I think it might be possible to implement a Manalyzer analyzer for Cortex-Analyzers 1.12.0.

**Comment by 3c7** [comment]
Currently in the process of integrating manalyze as FileInfo submodule.

**Comment by 3c7** [comment]
Finished and tested in #333 and ready for review/merge
