### ISSUE TITLE
[Bug][URLhaus_2_0] - Empty summary for positive results

### ISSUE THREAD

**Issue by 0xFustang** [TheHive-Project/Cortex-Analyzers#1210]
**Describe the bug**

When using analyzer URLhaus_2_0 I get an empty summary (` "summary": {},`) when having positive results.

**To Reproduce**

Search for any existing entry from URLHaus

**Expected behavior**

Having signatures of threat displayed as like https://github.com/TheHive-Project/Cortex-Analyzers/issues/431#issuecomment-466998834

**Complementary information**

Report example:

```
{
  "summary": {},
  "full": {
    "query_status": "ok",
    "id": "2700402",
    "urlhaus_reference": "https://urlhaus.abuse.ch/url/2700402/",
    "url": "http://117.219.119.158:47083/i",
    "url_status": "online",
    "host": "117.219.119.158",
    "date_added": "2023-08-06 11:29:05 UTC",
    "last_online": null,
    "threat": "malware_download",
    "blacklists": {
      "spamhaus_dbl": "not listed",
      "surbl": "not listed"
    },
    "reporter": "geenensp",
    "larted": "true",
    "takedown_time_seconds": null,
    "tags": [
      "32-bit",
      "elf",
      "mips",
      "Mozi"
    ],
```

**Work environment**

- Cortex version: latest stable
 - Cortex Analyzer/Responder name: URLhaus_2_0
- Cortex Analyzer/Responder version: 2.0

**Comment by nusantara-self** [comment]
Hello,

Just tried this specific example with current version (url `http://117.219.119.158:47083/i`), all works well on my side.

![image](https://github.com/user-attachments/assets/9d6ff9ea-4ada-400f-8cc3-ec1a5d9665fd)

Closing this issue
