### ISSUE TITLE
New Analyzer: QR Code Parser

### ISSUE THREAD

**Issue by bytinbit** [TheHive-Project/Cortex-Analyzers#1238]
**Feature description**
Parse images that contain a QR code and extract its contents.

**Describe the solution you'd like**
An analyzer that takes an observable of the type "file", and, if it's an image, checks for a QR code, parses it and returns the content. The result can be saved as new URL observable.

**Additional context**
I already have a working example and need to figure out how to submit it securely for review.

**Comment by EnzoCyberSec** [comment]
Working on it, will propose a pull request very soon.
