### ISSUE TITLE
MISP Warninglists analyzer

### ISSUE THREAD

**Issue by 3c7** [TheHive-Project/Cortex-Analyzers#124]
Currently [WIP](https://github.com/BSI-CERT-Bund/misp-warninglists-analyzer), the analyzer checks observables against the [misp-warninglists](https://github.com/MISP/misp-warninglists) to find potential false positives.
Creating PR after testing.

**Comment by saadkadhi** [comment]
Excellent @3c7. You read my mind as I had a similar idea upon my very fruitful discussions with @iglocska and @adulau.

**Comment by 3c7** [comment]
🔮
