### ISSUE TITLE
[FR] mail-subject dataType should be used instead of mail_subject

### ISSUE THREAD

**Issue by Guiiix** [TheHive-Project/Cortex-Analyzers#1260]
**Feature description**
All analyzers working with mail subjects are configured to accept **mail_subject** observable type. Howerver, since TheHive5, this observable type does not exist anymore and has been replaced by **mail-subject**.

**Describe the solution you'd like**
**mail-subject** dataType should be added to all analyzers compatible with **mail_subject** dataType

**Comment by nadouani** [comment]
Hi @Guiiix Thanks for the catch. PR merged
