### ISSUE TITLE
[Bug] Phistank analyzer failing

### ISSUE THREAD

**Issue by akshay-nehate** [TheHive-Project/Cortex-Analyzers#1276]
**Describe the bug**
Phistank analyzer fails to run

**To Reproduce**
1. Add API key
2. ![image](https://github.com/user-attachments/assets/599d27c2-9cb5-4ca6-b66d-57ea5fccf846)
3. ![image](https://github.com/user-attachments/assets/e8064352-6652-46ac-959f-5ae14bb6ce60)

**Expected behavior**
Works using curl command - 
```
curl -X POST "https://checkurl.phishtank.com/checkurl/" -H "User-Agent: phishtank/redacted" -d "url=https%3A%2F%2Fwww.example.com%2F" -d "format=json" -d "app_key=redacted" | jq

{
  "meta": {
    "timestamp": "2024-08-22T00:08:08+00:00",
    "serverid": "e5f3084e",
    "status": "success",
    "requestid": "172.17.128.1.66c68168d92ae9.71895076"
  },
  "results": {
    "url": "https://www.example.com/",
    "in_database": true,
    "phish_id": 2489536,
    "phish_detail_page": "http://www.phishtank.com/phish_detail.php?phish_id=2489536",
    "verified": true,
    "verified_at": "2014-06-03T10:01:24+00:00",
    "valid": false
  }
}
```

**Complementary information**
If applicable, add screenshots and any additional information that might help explain your problem.

**Work environment**
 - Browse type and version: **Version 127.0.6533.120 (Official Build) (64-bit)**
- Cortex version: **3.1.8-1**
- Cortex Analyzer/Responder name: **PhishTank_CheckURL_2_1**

**Comment by nusantara-self** [comment]
Thanks for the report Akshay!

PR #1271 should fix it
