### ISSUE TITLE
[Bug] OpenCTI Analyzer

### ISSUE THREAD

**Issue by adilraad2001** [TheHive-Project/Cortex-Analyzers#1280]
**Describe the bug**
Hello I try to do analyse by using opencti analyzer of cortex but i find when the observable in not in the opencti database i get success in the analyse but when is it exist i  get failed  for the analyse is there any solution of this
 
**Complementary information**
Example if i chose the ip address of google or any website i  have it already in OpenCTI as obsevable i get Failed
but when i use local address or an ip i knew is not exist i get success

**Work environment**
- Cortex version: 3.1.8-1
 - Cortex Analyzer/Responder name: OpenCTI_SearchObservables_2_0 |  OpenCTI_SearchExactObservable_2_0
- Cortex Analyzer/Responder version: 2_0

**Additional context**
IS there anny solution to this issue:

this is the erreur i find it in log file
<img width="761" alt="Screenshot 2024-09-10 123303" src="https://github.com/user-attachments/assets/79616ebb-d569-44da-b6ca-c02c98a94dd5">

**Comment by alghisic3k** [comment]
same issue here.

**Comment by adilraad2001** [comment]
> same issue here.

Hi i do my research about this erreur and i check the previous Bug and i find for fix it u need to do some change in the analyzer u can fin it there:
[1253](https://github.com/TheHive-Project/Cortex-Analyzers/pull/1253/commits/e3208a7724239f005fae75e3c73afd4db910ef3f)
