### ISSUE TITLE
[FR] Fix the version of TheHive4py dependencies in existing responders

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/Cortex-Analyzers#1281]
**Feature description**

Some responders rely on TheHive4py version 1.x, we need to update their requirements.txt file to specify the dependency version as TheHive4py 2.x is going to be released soon and it's a complete rewrite of the sdk.

**Comment by nadouani** [comment]
cc @kamforka

**Comment by nadouani** [comment]
cc @nusantara-self for information

**Comment by Kamforka** [comment]
The idea is to pin the 1.x version of thehive4py or upgrade to use 2.x?

**Comment by nadouani** [comment]
pin the 1.x :)
