### ISSUE TITLE
Urlscan Analyzer

### ISSUE THREAD

**Issue by Vince147** [TheHive-Project/Cortex-Analyzers#131]
### Request Type
Analyzer

### Work Environment
N/A

### Description
Create an analyzer using Urlscan.io api. Urlscan is another service similar to Urlquery to scan URL to search urls, files, etc.

**Comment by Vince147** [comment]
I will check with the owner of that service if that ok.

**Comment by Vince147** [comment]
Email was sent. Waiting for Urlscan answer.

**Comment by Vince147** [comment]
Still no answer.

**Comment by Vince147** [comment]
Alright i will start the coding.

**Comment by 3c7** [comment]
Hey @Vince147, how's the status on this one? Need help?

**Comment by heywoodlh** [comment]
I'm just getting into Hive/Cortex and never developed anything for it, but I've written a Python based API wrapper for urlscan.io: https://github.com/heywoodlh/urlscan-py. 

Perhaps this could help with the integration? If I can help at all I would love to.

**Comment by mhgeay** [comment]
Hello @heywoodlh, @Vince147,
If you need help on that, ping me !
Good luck

**Comment by heywoodlh** [comment]
Yeah, I would love to help but don't know how to start. Please let me know the best way to contact you @mhgeay

**Comment by 3c7** [comment]
Hello @heywoodlh,

there is some documentation about how to create an analyzer: https://github.com/TheHive-Project/CortexDocs/blob/master/api/how-to-create-an-analyzer.md#writing-an-analyzer.

Does it help you how to get started? Do you have specific questions?

**Comment by 3c7** [comment]
There's also a gitter channel (https://gitter.im/TheHive-Project/TheHive) with people who are willing to help.

**Comment by BrevilleBro** [comment]
Hi,

We are currently building this analyser. We have built the Python component and are currently working on the template for it.

**Comment by mhgeay** [comment]
@BrevilleBro Ok great, no need to do the same stuff ! tell me if you need help for the documentation.

**Comment by BrevilleBro** [comment]
Hi @mhgeay, please feel free to modify the code to your liking and submit a PR with improvements if necessary.

I have released our initial version: https://github.com/BrevilleBro/cortex-analyzer-urlscanio

Please test it out, if all is good and working I will submit a PR to this repo.

**Comment by ninoseki** [comment]
Hi all, I've created a yet another urlscan.io analyzer.
https://github.com/ninoseki/cortex_urlscan_analyzer
It doesn't make a scan request, just only makes a search by ip, domain, hash or url.
(Because in my use case, I don't want to make a scan via the analyzer)

How is this?

**Comment by 3c7** [comment]
Merged @ninoseki's PR.
