### ISSUE TITLE
BlueCoat Malware Analysis Sandbox Analyzer 

### ISSUE THREAD

**Issue by orbital-github-user** [TheHive-Project/Cortex-Analyzers#145]
## Request Type

Feature
## Description

Adding a new analyzer for Cortex : BlueCoat Malware Analysis Sandbox (https://www.bluecoat.com/en-gb/node/8027#readmore)

Would be great if we could:
+ Submit a file and detonate/open it in the sandbox, retrieve report in TheHive
+ Submit URL and open in sandbox, retrieve report/screenshots in TheHive
+ Etc.

**Comment by 3c7** [comment]
Bluecoat was acquired by Symantec - is this still relevant @orbital-github-user?

**Comment by jeromeleonard** [comment]
No answer, so closing it. If still interesting, reopen it.
