### ISSUE TITLE
CISCO AMP Sandbox Analyzer

### ISSUE THREAD

**Issue by orbital-github-user** [TheHive-Project/Cortex-Analyzers#146]
## Request Type

Feature
## Description

Adding a new analyzer for Cortex : CISCO AMP Sandbox ([https://www.cisco.com/c/en/us/products/security/advanced-malware-protection/index.html#~stickynav=1](https://www.cisco.com/c/en/us/products/security/advanced-malware-protection/index.html#~stickynav=1))

Would be great if we could:
+ Submit a file and detonate/open it in the sandbox, retrieve report in TheHive
+ Submit URL and open in sandbox, retrieve report/screenshots in TheHive
+ Etc.

**Comment by maugertg** [comment]
I am actively working on an Analyzer for Cisco Threat Grid

**Comment by LaZyDK** [comment]
This issue can be closed.

**Comment by dadokkio** [comment]
thanks :)
