### ISSUE TITLE
Issue with Cuckoo Sanbox Analyzer

### ISSUE THREAD

**Issue by mikjkd** [TheHive-Project/Cortex-Analyzers#148]
Analyzer 

Describe your request as clearly as possible.
Hi i have some troble with Cuckoo Sandbox Analyzer, it not run.

### Steps to Reproduce
1)Run Cortex
2)Select Cuckoo Sandbox file Inet analyzer
3)Upload file
4)Run analyzer

### Complementary information
when i upload a file for analyze, and run cuckoo sandbox analyzer i have this error message:
{
  "errorMessage": "Unexpected Error: Expecting value: line 2 column 1 (char 1)",
  "input": {
    "tlp": 1,
    "dataType": "file",
    "content-type": "application/x-ms-dos-executable",
    "filename": "Windows Loader.exe",
    "file": "/tmp/cortex-7407455047719042116-datafile",
    "config": {
      "url": "http://127.0.0.1:8000",
      "max_tlp": 1,
      "check_tlp": true,
      "service": "file_analysis"
    }
  },
  "success": false
}

So i run analyzer from The Hive and i have this error message:

Error: Invalid output Traceback (most recent call last): File "./cuckoosandbox_analyzer.py", line 136, in <module> CuckooSandboxAnalyzer().run() File "./cuckoosandbox_analyzer.py", line 130, in run self.error(e) File "/usr/local/lib/python2.7/dist-packages/cortexutils/analyzer.py", line 183, in error ensure_ascii=ensure_ascii) File "/usr/lib/python2.7/json/__init__.py", line 189, in dump for chunk in iterable: File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode for chunk in _iterencode_dict(o, _current_indent_level): File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict for chunk in chunks: File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode o = _default(o) File "/usr/lib/python2.7/json/encoder.py", line 184, in default raise TypeError(repr(o) + " is not JSON serializable") TypeError: ConnectionError(ProtocolError('Connection aborted.', error(32, 'Broken pipe')),) is not JSON serializable {"input": {"tlp": 1, "dataType": "file", "config": {"url": "http://127.0.0.1:8000", "max_tlp": 1, "check_tlp": true, "service": "file_analysis"}, "filename": "Windows Loader.exe", "attachment": {"id": "2f2aba1e074f5f4baa08b524875461889f8f04d4ffc43972ac212e286022ab94", "hashes": ["2f2aba1e074f5f4baa08b524875461889f8f04d4ffc43972ac212e286022ab94", "0efc35935957c25193bbe9a83ab6caa25a487ada", "323c0fd51071400b51eedb1be90a8188"], "contentType": "application/x-ms-dos-executable", "name": "Windows Loader.exe", "size": 4021049}, "file": "/tmp/cortex-6247224232316508378-datafile", "content-type": "application/octet-stream"}, "errorMessage": 

Can please someone help me?

**Comment by crackytsi** [comment]
See also #114.
I have the same issue sometimes

**Comment by nicpenning** [comment]
This still occurs on the latest 3.3.0-RC5 TH and 
Cortex2.1.3-1
Elastic4Play1.7.2
Play2.6.20
Elastic4s5.6.6
ElasticSearch client 5.6.9
ElasticSearch cluster 5.6.15

But it only seems to happen the once and for the first time when it is a new day. I have not been able to have this issue occur repeatedly outside of the first time trying to run it every morning.

![image](https://user-images.githubusercontent.com/5582679/54033979-64d56400-417b-11e9-97bc-0d11521d0edd.png)

After the failure it works great for the remainder of the day.

**Comment by jeromeleonard** [comment]
Does this issue still exist ?

**Comment by garanews** [comment]
Hi @crackytsi , @mikjkd , which version of cuckoo sandbox are using?
I'm using v.2.0.7 and analyzer works as expected.

**Comment by garanews** [comment]
This seems to have stalled, perhaps it has been already solved in newer version of cuckoo. I'm therefore closing it, but feel free to reopen if that's still an issue.
