### ISSUE TITLE
Malpedia (yara) Analyzer

### ISSUE THREAD

**Issue by garanews** [TheHive-Project/Cortex-Analyzers#166]
### Request Type
Analyzer

### Description
 Malpedia is a free service offered by Fraunhofer FKIE: https://malpedia.caad.fkie.fraunhofer.de/
Administration is lead by Daniel Plohmann, who also bootstrapped Malpedia with data on roundabout 450 families.
The website has been designed and programmed by Steffen Enders.
Mission Statement:
The primary goal of Malpedia is to provide a resource for rapid identification and actionable context when investigating malware. Openness to curated contributions shall ensure an accountable level of quality in order to foster meaningful and reproducible research.

**Comment by garanews** [comment]
#167

**Comment by 3c7** [comment]
Merged!
