### ISSUE TITLE
PayloadSecurity analyzer sslverify config conversion bug.

### ISSUE THREAD

**Issue by K-marad** [TheHive-Project/Cortex-Analyzers#185]
### Request Type
Bug

### Description
In PayloadSecurity analyzer, the current code does :
```
self.verify = self.getParam('config.verifyssl', True, None)

response = requests.post(self.url.strip('/') + '/api/submit', data=data, headers=user_agent,
                                         files=files, auth=HTTPBasicAuth(self.apikey, self.secret), verify=self.verify)
```

The problem is that self.verify is a unicode object, not a boolean.
So requests thinks that self.verify is the path to the local SSL certificates and uses it as such.
Which leads to a FileNotFound error.

### Steps to Reproduce
Normal usage...

### Possible Solutions
config.verifyssl should be parsed as a boolean.
ex: 
`self.verify = self.getParam('config.verifyssl', True, None) in ['True', 'true', True]`

### Quick fix 
Remove sslverify from configuration (default value is True as a boolean)

**Comment by 3c7** [comment]
`requests`, the python module that queries the API, takes Boolean and Strings as verify param for the given methods. Valid values for `config.verifyssl` are therefore:
- `true`
- `false`
- `/path/to/cert.pem`

**Comment by jeromeleonard** [comment]
So can we close this issue ?

**Comment by jeromeleonard** [comment]
No answer, so closing it.
