### ISSUE TITLE
Cuckoo Analyzer changes the name of the file

### ISSUE THREAD

**Issue by mlodic** [TheHive-Project/Cortex-Analyzers#188]
### Request Type
Feature

### Description
I noticed that every time I send a file to the Cuckoo Analyzer, the file is called like this:
`cortex-<number>-datafile`
I think that it would be really useful if the original file name was kept. Otherwise, I lose an important information when I am looking for the analysis directly from Cuckoo.

### Possible Solutions
Change the pattern used like one of the following one:
`cortex-<filename>-datafile`
`cortex-<number>-datafile-<filename>`

Thank you very much for the work done in this project! :)

**Comment by garanews** [comment]
In this way it is working keeping the original filename: https://github.com/LDO-CERT/Cortex-Analyzers/commit/80aa6a4b1bc46ad1adbc781f3e9249c2cd1e0be0#diff-4f9672beff6f37b6d35a9b3cc309c64a



![cuckoo_file](https://user-images.githubusercontent.com/16938405/36375763-e6d9000c-1570-11e8-967e-0cf5d9000b05.png)



Thanks for reporting

**Comment by mlodic** [comment]
Yes, this fix solves the issue! Thank you very much!
