### ISSUE TITLE
Feature Request: haveibeenpwned.com

### ISSUE THREAD

**Issue by Edward-merrett** [TheHive-Project/Cortex-Analyzers#189]
# I would love to see a haveibeenpwned.com Analyser, would tie in well with DataBreach intel.)

### Analyser
Would love to work with someone to create an analyser for haveibeenpwned.com.

https://haveibeenpwned.com/API/v2

**Comment by jcchristian** [comment]
#190

**Comment by 3c7** [comment]
Duplicate to #190 / #191
