### ISSUE TITLE
DomainTools authentication appears to be broken

### ISSUE THREAD

**Issue by armngar** [TheHive-Project/Cortex-Analyzers#206]
### Request Type
Bug
### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |Ubuntu Xenial running Docker 
| OS version (client)       | Windows 7
| Cortex Analyzer Name      | DomainTools
| Cortex Analyzer Version   | 
| Cortex Version            |  1.1.4
| Browser type & version    | n/a

### Description
Attempting to use a domaintools api token results in "Authorization Error".  Using a test domain (like domaintools.com) bypasses authentication and works perfectly.

### Steps to Reproduce
1. Add API username and key for domaintools
2. Attempt to run analyzer for any domain except for test domains (ie, domaintools.com)
3. Analyzer will fail.

### Possible Solutions
It appears that the analyzer uses a really old version of a python domain tools wrapper.  Domaintools provides their own API that is actively maintained here: https://github.com/DomainTools/python_api

**Comment by jeromeleonard** [comment]
Hi. the program has been updated to use the up to date official domaintools lib. It also should work with python2 and python3; have a look at dependencies for your version in requirements.txt.  If you can, please tell us if it fixed your issue (only works with Cortex >= 2.0.0 ). If success, this version should be quickly in master branch.
