### ISSUE TITLE
Analyzer Template Check-Up

### ISSUE THREAD

**Issue by 3c7** [TheHive-Project/Cortex-Analyzers#213]
Some reports (both, short and long) are not as useful as they could be, sometimes. This issue is for collecting improvements for the reports.

**Comment by 3c7** [comment]
@garanews mentioned that the MISP analyzer short report label should be more distinguishable (color).

**Comment by garanews** [comment]
Distinguish "found" vs "not found"

![image](https://user-images.githubusercontent.com/16938405/38088109-f9803c68-335a-11e8-90ae-6716d01ac930.png)

**Comment by garanews** [comment]
I added this (highlighted row) in misp.py:

![image](https://user-images.githubusercontent.com/16938405/38092602-04eda2d0-3369-11e8-96b1-45b99515cf7a.png)



Result: 
![image](https://user-images.githubusercontent.com/16938405/38092532-cbeafd66-3368-11e8-841b-be87d255998f.png)

**Comment by 3c7** [comment]
MISP short report changes :heavy_check_mark:

**Comment by jeromeleonard** [comment]
fixed.
