### ISSUE TITLE
Option to ignore SSL errors from analyzers

### ISSUE THREAD

**Issue by geekscrapy** [TheHive-Project/Cortex-Analyzers#228]
Some internally hosted workers for analyzers (e.g. Cuckoo) may not have a valid certificate. Can an option be created to disable SSL verification on certain analyzers?

**Comment by nadouani** [comment]
This could be made on the analyzers, one by one but needs development.

Please list the analyzers you want see with support of an option to disable SSL verification

**Comment by geekscrapy** [comment]
Fair enough - initially I guess the self-hosted workers would be a priority:

1. CuckooSandbox
2. MISP
3. Yeti
4. Nessus
5. VMRay

But essentially all may need this if Cortex has to go through a corporate proxy?

**Comment by saadkadhi** [comment]
@geekscrapy Is the solution provided by @3c7 satisfactory? Can we go ahead and close this issue?

**Comment by geekscrapy** [comment]
I haven't tried but I presume it wouldn't work for Dockerised analyzers and would require modification of the cortex docker file (appreciate this isn't hard to do)?

I think it would be best to have a dedicated SSL setting contained in the general analyzer settings?

**Comment by jeromeleonard** [comment]
this shoud be fixed in develop branch, please test it and get back to us. I added a verifyssl option in Cuckoo analyzers. Version has been bumped to 1.2
