### ISSUE TITLE
New DomainTools API services requires new analyzer

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/Cortex-Analyzers#240]
### Request Type

Feature

### Work Environment
N/A

### Description
We need a new analyzer for the new DomainTools Risk Score they have added to their subscription API. You get a Risk Score and a Proximity Score. Proximity is a guilty by association score. 

Sample of date returned from MISP Domain Tools Module:

Domain searched: acexportm[.]com
```
risk_score: 76, name: proximity, risk_score: 99, name: threat_profile, risk_score: 0, name: threat_profile_phishing, risk_score: 99, name: threat_profile_malware, risk_score: 0, name: threat_profile_spam
```
Could be based off of them: https://github.com/DomainTools/domaintools_misp

**Comment by saadkadhi** [comment]
@jeromeleonard I believe you worked on this already. Can you please update the labels & issue accordingly?

**Comment by jeromeleonard** [comment]
yes, this is a duplicate with https://github.com/TheHive-Project/Cortex-Analyzers/issues/214
