### ISSUE TITLE
Dockerising analyzers

### ISSUE THREAD

**Issue by geekscrapy** [TheHive-Project/Cortex-Analyzers#246]
I heard a while back there may be thoughts of dockerising analyzers. Is this correct? Any idea on the status of this?

TIA!

**Comment by 3c7** [comment]
Hey @geekscrapy, it's in this PR #171, but atm, I don't have that much time for development. But I'm planning to continue and merge the PR.

**Comment by 3c7** [comment]
FYI: nearly finished. Need to wait for a fix in Cortex 2.

**Comment by geekscrapy** [comment]
Any advancement on this? Mainly docs that describe setup of analyzers in docker.

Use case for me is to have every analyzer dockerized to be able to block network connectivity for certain analyzers to provide confidence they are not leaking TLP :AMBER and RED data.

**Comment by jeromeleonard** [comment]
done. Working with cortex 3.x version.
