### ISSUE TITLE
New analyzer: malwares.com

### ISSUE THREAD

**Issue by garanews** [TheHive-Project/Cortex-Analyzers#251]
### Request Type
 Analyzer 

### Description
malwares.com API based on web is designed to link with various systems of customers so that customers can use cyber threat intelligence.
It is a programming interface to request a lot of analysis results inmalwares.com and search them.

You can enjoy a great deal of malicious codes data or related information quickly and efficiently.
You can get automatically the analyzed data and deal with huge amount of data as well. For more information, please refer to malwares.com API documentation as below.

Members of malwares.com can search 100 requests per day (50 requests per day for some of request items) for free.
(File Download API is only for charged service members)

**Comment by garanews** [comment]
done https://github.com/TheHive-Project/Cortex-Analyzers/pull/252
![image](https://user-images.githubusercontent.com/16938405/40495016-7a5e28ee-5f76-11e8-8eb9-7bfeb5135c68.png)
![image](https://user-images.githubusercontent.com/16938405/40495034-83374b94-5f76-11e8-95dd-2db6aa36f22b.png)
![image](https://user-images.githubusercontent.com/16938405/40495045-8b25e9dc-5f76-11e8-8ebc-01357778f515.png)
![image](https://user-images.githubusercontent.com/16938405/40495069-94c94452-5f76-11e8-993e-627dfa096071.png)
![image](https://user-images.githubusercontent.com/16938405/40495122-bbab7428-5f76-11e8-97b5-215db5b23df4.png)

**Comment by 3c7** [comment]
Merged, see #252.
