### ISSUE TITLE
New Analyzer: Mnemonic PDNS (Public & Closed)

### ISSUE THREAD

**Issue by NFCERT** [TheHive-Project/Cortex-Analyzers#255]
### Request Type
Analyzer

### Description
https://www.mnemonic.no/news/2015/mnemonic-offers-passive-dns-data-to-the-public/

> mnemonic will also exchange passive DNS data with selected partners. These data are not available to the public, but will be available for our partners once suitable agreements have been made. As of July 1st 2014, the database contains in excess of 530 million entries, of which 60 million are "TLP WHITE".
>
> We will be offering a JSON API available over HTTP.  For an API description, please contact mss [a] mnemonic [dot] no.

Build support for Public and Closed analyzer's.

#### Public Analyzer
- Search in anonymized PDNS data 

#### Closed Analyzer
- Search in own PDNS data

**Comment by garanews** [comment]
Solved with https://github.com/TheHive-Project/Cortex-Analyzers/pull/256
