### ISSUE TITLE
Install analyzers in Red Hat Enterprise 7

### ISSUE THREAD

**Issue by jezkerwin** [TheHive-Project/Cortex-Analyzers#257]
Has anyone successfully installed the analyzers on RHEL 7?

I'm trying to get them working and I think the need for python 2 and 3 are causing issues.

Can rhey be installed using software collections (rhscl)?

**Comment by jezkerwin** [comment]
I'm going to close this, because I believe my particular issue is the default UMASK during analyzer install caused the issue.

**Comment by k3rnon** [comment]
> I'm going to close this, because I believe my particular issue is the default UMASK during analyzer install caused the issue.

Hello m8! Can You tell me...Did You handle it? I have same issue;/ I wanted to install thehive on redhat... All works fine but have problem with cortex-analazer.... its empty... dunno how to install them;/

**Comment by jezkerwin** [comment]
Hi, I did get it working, it wasn't what I thought it was originally.
Because I was using software collections rhscl, I needed to modify the systemd startup file to run scl python27 and rh-python36 to be able to run the analyzers.

I can't get to the install right now, but when I'm next there I'll see if it's still set the same way

**Comment by k3rnon** [comment]
thank you for your answer! Wow that was really quick:)
