### ISSUE TITLE
Phishtank checkURL fails

### ISSUE THREAD

**Issue by stacsirt** [TheHive-Project/Cortex-Analyzers#261]
Bug 

### Work Environment
N/A

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | OSX
| Cortex Analyzer Name      | PhishTank_CheckURL
| Cortex Analyzer Version   | 2.1
| Cortex Version            | 2.0.4
| Browser type & version    | Firefox 60.0.1

### Description
When attempting to look up an URL in the analyser (from Cortex), I get the following error;

Invalid output
Traceback (most recent call last):
  File "PhishTank/phishtank_checkurl.py", line 73, in <module>
    PhishtankAnalyzer().run()
  File "PhishTank/phishtank_checkurl.py", line 44, in run
    r = self.phishtank_checkurl(data)
  File "PhishTank/phishtank_checkurl.py", line 19, in phishtank_checkurl
    return json.loads(r.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

### Steps to Reproduce
(keep this section only if the issue relates to a bug)
1. Start New Analysis
2. Enter URL (www.example.com)
3. Run analyser

Requirement already up-to-date: cortexutils in /usr/local/lib/python3.5/dist-packages (1.2.4)

thanks for any help!

**Comment by jeromeleonard** [comment]
Hi,

can't reproduce the error on my side, everything works fine. Could you please confirm the error and give sample URLs please ? 

Thanks.

**Comment by stacsirt** [comment]
Interesting - thank you for checking. I have done some work on the install of python and it seems to work now. Feel free to close this as user error.
