### ISSUE TITLE
Payloadsecurity

### ISSUE THREAD

**Issue by stacsirt** [TheHive-Project/Cortex-Analyzers#262]
Bug

N/A

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | OSX
| Cortex Analyzer Name      | Payloadsecurity (url or file) v1
| Cortex Analyzer Version   | 2.1
| Cortex Version            | 2.0.4
| Browser type & version    | Firefox 60.0.1

### Description
When submitting a URL or file through the payload security analyzer, it fails with a 'environment id is missing) - even though it has been specified.

### Steps to Reproduce
1. Run analyzer
2. Give it a file or URL to check
3. Submit

### Possible Solutions
Possibly a typo in payloadsecurity_analyzer.py

diff payloadsecurity_analyzer.py payloadsecurity_analyzer.py.orig
16c16
<         self.environmentid = self.get_param('config.environmentId', None, 'PayloadSecurity environmentid is missing')
---
>         self.environmentid = self.get_param('config.environmentid', None, 'PayloadSecurity environmentid is missing')

Hope that helps!

**Comment by jeromeleonard** [comment]
Thanks you @stacsirt. Updating the analyzer with ```environmentId```.
