### ISSUE TITLE
New analyzer : Google Vision API 

### ISSUE THREAD

**Issue by 0xswitch** [TheHive-Project/Cortex-Analyzers#298]
Hi,

I just finished to develop a new analyser based on the [Google Cloud API Vision](https://cloud.google.com/vision/).

This analyser accept an image via an url or directly with the file and ask this API in order to get a list of website using this image and look alike image.

It can be usefull for data leak or to find phishing web site using known images.

Pull request #297

**Comment by garanews** [comment]
addressed with https://github.com/TheHive-Project/Cortex-Analyzers/pull/297
