### ISSUE TITLE
New analyzer: DShield

### ISSUE THREAD

**Issue by xme** [TheHive-Project/Cortex-Analyzers#299]
Hello,

I just published a small analyzer to query information from the DShield IP reputation database.
https://blog.rootshell.be/2018/07/09/dshield-analyzer-cortex/
Feel free to have a look, maybe it could be interesting for you?

**Comment by saadkadhi** [comment]
Hi @xme. Thanks for the analyzer. Please submit a PR.

**Comment by xme** [comment]
Done!
