### ISSUE TITLE
disable

### ISSUE THREAD

**Issue by Brainfold** [TheHive-Project/Cortex-Analyzers#301]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type
(select Bug, Analyzer or Feature and **remove this line**)
Bug / Analyzer / Feature

### Work Environment
(replace with N/A if not applicable)

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| Cortex Analyzer Name      | OTXQuery, PhishingInitiative, VirusTotal, ...
| Cortex Analyzer Version   | 1.0, 1.1, ...
| Cortex Version            | 1.0.0, hash of the commit
| Browser type & version    | If applicable

### Description
Describe your request as clearly as possible.

### Steps to Reproduce
(keep this section only if the issue relates to a bug)
1. step 1
1. step 2
1. step 3...

### Possible Solutions
(keep this section if you have suggestions on how to solve the problem. **Otherwise delete it**)

### Complementary information
(add anything that can help identifying the problem such as **logs**, **screenshots**, **configuration dumps** etc.)

**Comment by saadkadhi** [comment]
This issue is an unedited template.
