### ISSUE TITLE
New analyzer : Google DNS over HTTPS 

### ISSUE THREAD

**Issue by 0xswitch** [TheHive-Project/Cortex-Analyzers#306]
Hi,

I just finished to develop a new analyser based on the Google DNS resolver over HTTPS

This analyzer accepts ip, domain and fqdn observable and return the different associated provided by this google service. 

There are already analyzer who provides DNS records however this one is free and doesn't need an api key. Moreover it can be used behind a corporate proxy which allow only http and https flux.

PR #305

**Comment by jeromeleonard** [comment]
see #305
