### ISSUE TITLE
Could not get Yeti analyzer worked in cortex

### ISSUE THREAD

**Issue by shubhamblackstratus** [TheHive-Project/Cortex-Analyzers#307]
I have installed Cortex and Yeti in my single machine and both are worked properly while calling from browsers. But while configuring and running Yeti through cortex analyzers, I got the below error : 

**Service unavailable, please check if Yeti server is running**. 

Find the snaps for errors. 

![2](https://user-images.githubusercontent.com/25363342/42900840-90b5987e-8ae7-11e8-9a09-e92a579c3a93.jpg)
![yeti](https://user-images.githubusercontent.com/25363342/42900876-a761f8e2-8ae7-11e8-8d33-a7dbf4f2a14f.jpg)

**Comment by shubhamblackstratus** [comment]
Error is Chaned now, after installing django...

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/observablesearch/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa95b88cb10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by shubhamblackstratus** [comment]
Hi Team, 

Can you please help me asap....? 

Thanks...

Shubham

**Comment by jeromeleonard** [comment]
Could you please ensure that you are looking for is really in Yeti database ? It seems that this error is also received when the response from Yeti is empty ? 

Thanks

**Comment by shubhamblackstratus** [comment]
I have gone through docs to integrate Yeti with Cortex and as per my understanding, one needs to make Yeti instance perfectly run in the same machine in which Cortex is installed. 

I have made both running smoothly in the same machine but due to lake of python knowledge I could not recognize an error.

Even I could not get anything except the reported log. 

I wanted to configure Yeti as an analyzer working in Cortex GUI. Kindly guide what I should do next.

**Comment by shubhamblackstratus** [comment]
It could be understood that it might be some response problem from Yeti but it gets worked while opening from localhost. See snap. 

I have gone through docs to integrate Yeti with Cortex and as per my understanding, one needs to make Yeti instance perfectly run in the same machine in which Cortex is installed. So I have made both running smoothly in the same machine but due to low python knowledge I could not recognize an error.

Even I could not get anything except the reported log. 

I wanted to configure Yeti as an analyzer working in Cortex GUI. Kindly guide what I should do next. 

I appreciate your response and suggestions. 

Thanks..!

**Comment by jeromeleonard** [comment]
try : 
1. add an observable in Yeti
2. Run Yeti analyzer in Cortex or TheHive to look for this observable

This should work.
