### ISSUE TITLE
ClamAV New analyzer

### ISSUE THREAD

**Issue by Hestat** [TheHive-Project/Cortex-Analyzers#311]
### Request Type
Analyzer

ClamAV has become a very useful open source AV and general purpose scanner. I find it most useful in being able to parse Yara rules and the inclusion of sigtool to create your own Clam rule sets.

While I run this locally on many linux servers with my own script. I often have new samples that are not in my existing rules, I've wanted a way to be able to ingest my rules into TheHive, I was using the yara analyzer but it has had some hiccups with v2 of Cortex. This led me to build the following using the base code from other scanners:

https://github.com/Hestat/ClamAV-CortexAnalyzer

I believe it it at a functional level now and wanted to share with the community.

**Comment by garanews** [comment]
Added in 2.5.0
