### ISSUE TITLE
Wrong File handling in OTXQuery Analyzer

### ISSUE THREAD

**Issue by sevdog** [TheHive-Project/Cortex-Analyzers#313]
Wrong File handling in OTXQuery Analyzer

### Request Type
Bug

### Work Environment
N/A

### Description
In OTXQuery `otxquery` module the file is mishandled during hash calculation, this may cause various problems:
```
hash = hashlib.sha256(open(filepath, 'r').read()).hexdigest();
```
Problems are:

1. file handler is never closed
2. for hash calculation open mode should be _binary_ (`rb`)
3. if the file is big this operation will be very slow and will use a lot of memory

### Possible Solutions
1. The file should be opened using a `with` statement (aka context manager), as also suggested by [python language guidelines](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files)

> It is good practice to use the `with` keyword when dealing with file objects
2. The file should be opened in _binary mode_: `rb`
3. Reads should be performed per _chunk_ as suggested in [this post on SO](https://stackoverflow.com/a/519653) and also like [django does][(https://docs.djangoproject.com/en/2.0/_modules/django/core/files/base/#File.chunks)
4. Remove trailing semicolon (`;`)

**Comment by 3c7** [comment]
Thanks for reporting. Fixed in 1.15.2.
