### ISSUE TITLE
New Analyser: Strings

### ISSUE THREAD

**Issue by j-i-m-b-o** [TheHive-Project/Cortex-Analyzers#315]
### Request Type
 Analyzer 

### Description
I have submitted a PR here #314 for a strings analyser I use within my organisation. The analyser takes an observable of type file and extracts any printable strings. While I appreciate this is quite a simple analyser I have personally found it a useful first step when dealing with various unknown files.

**Comment by nadouani** [comment]
This is part of File Info analyzer, closing.
