### ISSUE TITLE
PassiveTotal_Passive_Dns_2_0 ordering issue

### ISSUE THREAD

**Issue by ninoseki** [TheHive-Project/Cortex-Analyzers#329]
### Request Type

Bug(?)

### Description

PassiveTotal_Passive_Dns_2_0 ordering issue

`PassiveTotal_Passive_Dns_2_0` is a good analyzer but there is a point could be improved IMHO.
The point is ordering in the template.
The current template shows records with without no specific ordering.

**Current template report**
![Imgur](https://i.imgur.com/jRJBCfB.png)

### Possible Solutions

It would be good if specifying an order of records. (e.g. `orderBy:'-firstSeen'`)

**`orderBy:'-firstSeen'`report**
![Imgur](https://i.imgur.com/pl1RUTT.png)

**Comment by 3c7** [comment]
Merged, thanks @ninoseki !
