### ISSUE TITLE
Cortex-analyzer deb package?

### ISSUE THREAD

**Issue by vfidalgo** [TheHive-Project/Cortex-Analyzers#336]
### Request Type
 Feature

### Work Environment
(replace with N/A if not applicable)

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 
| OS version (client)       | Strech
| Cortex Analyzer Name      | N/A
| Cortex Analyzer Version   |  N/A
| Cortex Version            | 2.0.4
| Browser type & version    | If applicable

### Description
It Has any way to make a package (like cortex and thehive deb) to launch cortex-analyzers i have a lot of problems with the pip versions?

**Comment by nadouani** [comment]
Hello,  I don't think this can make sense to have deb packages for analyzers, but we plan to dockerize them to get rid of all the dependencies issues.

That said, what pip issues do you encounter? I could be related to your pip installation or permissions etc...

**Comment by vfidalgo** [comment]
I have problems with cortex analyzers in the configuration, this analyzer not appear when enter how orgadmin, follow the issue https://github.com/TheHive-Project/Cortex/issues/88 and not resolved then. 

I think is by the pip dependencies installation but i not sure, my application.conf is 

'''analyzer {
  # Absolute path where you have pulled the Cortex-Analyzers repository.
  path = ["/opt/cortex/Cortex-Analizers/analyzers"]

  # Sane defaults. Do not change unless you know what you are doing.
  fork-join-executor {

    # Min number of threads available for analysis.
    parallelism-min = 2

    # Parallelism (threads) ... ceil(available processors * factor).
    parallelism-factor = 2.0

    # Max number of threads available for analysis.
    parallelism-max = 4
  }
}''''

**Comment by nadouani** [comment]
Honestly installing analyzer is really straight forward, you just need to follow the [Quick Guide](https://github.com/TheHive-Project/CortexDocs/blob/master/admin/quick-start.md)

If you have configuration issues etc... please lets discuss it on Gitter, so all the community can help.
