### ISSUE TITLE
CERTatPassiveDNS_2_0 Invalid File for WHOIS.sh

### ISSUE THREAD

**Issue by scrublullz** [TheHive-Project/Cortex-Analyzers#349]
### Request Type
Bug

### Description
When executing a query using CERTatPassiveDNS, the response comes back with an error:  
`FileNotFoundError: [Errno 2] No such file or directory: './whois.sh': './whois.sh'`

### Possible Solutions
Submitted the following commit to pull the current file path of `whois_wrapper.py` in order to define the full path of `whois.sh`

https://github.com/TheHive-Project/Cortex-Analyzers/commit/1f6f1ddf9c5c513257f72853d4fe0e4ac6e32640

**Comment by 3c7** [comment]
Should be fixed by now (fa8658432d3dbaa0e44a96c397ac7ad6bccf3035). Forgot to close the issue. Thanks for reporting!

**Comment by geekscrapy** [comment]
Just updated this analyzer from within the cortex docker container and it now has the following error:

```
Failure, Invalid output
/opt/Cortex-Analyzers/analyzers/CERTatPassiveDNS/whois.sh: line 2: whois: command not found
Traceback (most recent call last):
  File "CERTatPassiveDNS/certat_passivedns.py", line 38, in <module>
    CERTatPassiveDNSAnalyzer().run()
  File "CERTatPassiveDNS/certat_passivedns.py", line 18, in run
    self.report({'results': query(self.get_data(), int(self.limit))})
  File "/opt/Cortex-Analyzers/analyzers/CERTatPassiveDNS/whois_wrapper.py", line 58, in query
    return __process_results(__query(domain, limit))
  File "/opt/Cortex-Analyzers/analyzers/CERTatPassiveDNS/whois_wrapper.py", line 17, in __query
    s = check_output(['{}'.format(os.path.join(os.path.dirname(__file__), 'whois.sh')), '--limit {} {}'.format(limit, domain)], universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/Cortex-Analyzers/analyzers/CERTatPassiveDNS/whois.sh', '--limit 100 example.com']' returned non-zero exit status 127.
```

**Comment by 3c7** [comment]
Please install `whois`. By the way, are you whitelisted for using the service?
