### ISSUE TITLE
Joe Sandbox Analyzer returning error with Joe Sandbox Cloud Pro

### ISSUE THREAD

**Issue by schoad** [TheHive-Project/Cortex-Analyzers#357]
Joe Sandbox Analyzer not working.

### Request Type
Analyzer

### Work Environment
N/A

### Description
Joe Sandbox Analyzer not working with Joe Sandbox Cloud Pro.

### Possible Solutions
Already tried to modifiy the joesandbox_analyzer.py (systems parameter changed from null to auto or w10x64_1803). 
Same error.

### Complementary information
1. Using the latest TrainingVM (October 14th)
2. Default JoeSandbox Analyzer 
3. API endpoint https://jbxcloud.joesecurity.org/api/
4. API Key works (tested with Postman, e.g. get systems with POST /api/v2/server/systems HTTP/1.1
Host: jbxcloud.joesecurity.org)
5. Results =

{
"errorMessage": "Unexpected Error: Expecting value: line 1 column 1 (char 0)",
"input": "{\
"pap\":2,\
"tlp\":2,\
"contentType\":\"application/vnd.oasis.opendocument.text\",\
"parameters\":{},\
"dataType\":\"file\",\
"filename\":\"OOText.Embedded.Eicar.odt\",\
"file\":\"/tmp/cortex-job-XYZ\",\
"message\":\"\",\
"config\":{\"networktimeout\":30,\
"check_pap\":true,\
"check_tlp\":true,\
"proxy_https\":null,\
"service\":\"file_analysis_noinet\",\
"url\":\"https://jbxcloud.joesecurity.org/api/\",\
"max_tlp\":2,\
"auto_extract_artifacts\":false,\
"proxy_http\":null,\
"key\":\"REMOVED\",\
"analysistimeout\":1800,\
"max_pap\":2}}",
  "success": false
}

**Comment by saadkadhi** [comment]
@schoad you must not point it to the API endpoint but to the service URL as requested by the analyzer:
<img width="885" alt="screenshot_2018-10-18_at_13_57_41" src="https://user-images.githubusercontent.com/2852427/47152778-ed8f5880-d2dd-11e8-9b2a-6dea1f123114.png">
