### ISSUE TITLE
Virusshare analyzer: suggesting another way to retrieve hash file names

### ISSUE THREAD

**Issue by garatc** [TheHive-Project/Cortex-Analyzers#359]
https://github.com/TheHive-Project/Cortex-Analyzers/blob/fd12ec8e9eb2aba1e4eb0280edd94e8118976e11/analyzers/Virusshare/getHashes.sh#L24

This line doesn't work for me.
I had to replace it with 
for u in `curl https://virusshare.com/hashes.4n6 | grep -E "VirusShare_[0-9]{5}\.md5" | cut -c17-36`

**Comment by garanews** [comment]
Just tried the script and I confirm is not working (getting "failed writing body").
In my case I am using 
```
for u in `curl https://virusshare.com/hashes.4n6 | grep -E "VirusShare_[0-9]{5}\.md5" | c\
ut -d\" -f2 | cut -d\/ -f2`
```
We can fix in this way.

**Comment by garanews** [comment]
This is already fixed in master branch.
