### ISSUE TITLE
Force python3 in all analyzers

### ISSUE THREAD

**Issue by jeromeleonard** [TheHive-Project/Cortex-Analyzers#361]
Review all analyzer and make them working with python3 (at leat, try to :)  )

List of analyzers that might be reviewed : 

- [x] Abuse_Finder
- [x] StopForumSpam
- [x] MaxMind
- [x] Virustotal

### Doc

- [ ] Update "How to create an analyzer" 

**To be completed**

**Comment by LetMeR00t** [comment]
Hi guys,
I proposed this PR for Abuse_Finder but it will need another PR (in the repository abuse_finder) to be used :
https://github.com/TheHive-Project/Cortex-Analyzers/pull/469

**Comment by nadouani** [comment]
Same thing for VirusTotal, the PR #446 solves the issue. We will merge these ASAP

**Comment by nadouani** [comment]
We need to UP this one

**Comment by nadouani** [comment]
@3c7 @jeromeleonard Do we need to update the the shebang statement of all the analyzers to replace `python` with `python3`?
