### ISSUE TITLE
OTXQuery_2_0 Error when submitting IP address 

### ISSUE THREAD

**Issue by jezkerwin** [TheHive-Project/Cortex-Analyzers#363]
When running the OTXQuery_2_0 analyser on an IP address, I'm getting the following error.

  "errorMessage": "API Error! Please verify data type is correct.",

I run the same IP address through the VirusTotal analyser and that works fine. I'm running through a proxy server but the VirusTotal analyser works.
No other information is being returned.

**Comment by nadouani** [comment]
This looks like this error might occur because of something else. The analyzer is working for some IP here. can you share the IP address that throws that error, if it's sharable? Thanks

**Comment by jeromeleonard** [comment]
closing until we get more details
