### ISSUE TITLE
[PATCH] Implement some other ONYPHE simple APIs (but still not the search API)

### ISSUE THREAD

**Issue by onyphe** [TheHive-Project/Cortex-Analyzers#372]
# Implement some other ONYPHE simple APIs (but still not the search API)

### Request Type
Feature

### Work Environment
N/A

### Description
Implements user, onionscan, sniffer, ctl and md5 simple APIs. But not the search APIs yet. Unfortunately, as we are not at easy with Python, we just sent the patch for onyphe_api.py and not for onyphe_analyzer.py.
[onyphe-patch.txt](https://github.com/TheHive-Project/Cortex-Analyzers/files/2569405/onyphe-patch.txt)

**Comment by nadouani** [comment]
Hello @onyphe 

do you think we need a custom analyzer template for each one of these new methods? or we just need to add an analyzer for user, onionscan, sniffer, ctl and md5, an reuse the existing report templates for TheHive?

Thanks

**Comment by onyphe** [comment]
Hello,

well, as we are not the original developers of the Cortex Analyzer and we don't have a real experience on how that works internally, it is quite difficult to answer your question. My guess would be to use the same scheme as previously used for other methods, as there is no difference in regards to our APIs.

So, I would say, go for a new analyzer for each new API. Field names are normalized between APIs, if that may help you take the right decision.

Best regards,


--
https://www.onyphe.io
Your Internet SIEM
Twitter: @onyphe

On 17/12/2018 13:38, Nabil Adouani wrote:

Hello @onyphe<https://github.com/onyphe>

do you think we need a custom analyzer template for each one of these new methods? or we just need to add an analyzer for user, onionscan, sniffer, ctl and md5, an reuse the existing report templates for TheHive?

Thanks

**Comment by dadokkio** [comment]
@onyphe is this issue still valid?

**Comment by onyphe** [comment]
Hello,

as we have moved to APIv2, this should not be a concern anymore.

Thank you,
