### ISSUE TITLE
MISP Analyzer only queries first configured MISP instance

### ISSUE THREAD

**Issue by ParanoidRat** [TheHive-Project/Cortex-Analyzers#378]
### Request Type
Bug

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Docker Swarm service
| OS version (client)       | N/A
| Cortex Analyzer Name      | MISP
| Cortex Analyzer Version   | 2.0
| Cortex Version            | 2.1.2
| Browser type & version    | N/A

### Description
I have two MISP instances configured with two values for `name`, `url`, `key`, `cert_path` (both pointing just to `/etc/ssl/certs`) and disabled server cert verification (`cert_check: false`).

When analyzer is invoked it returns results (including empty results for non-existent items) only from one instance. No errors in logs.

### Steps to Reproduce
1. Deploy Cortex as a service on Docker Swarm
1. Configure MISP analyzer with two MISP instances as described above
1. Search for something that does or does not exist in both (or one) instances

**Comment by 3c7** [comment]
Hey @ParanoidRat, I cannot reproduce the bug. If you want to use different MISP servers iwth regular trusted certificates, just leave the cert_path empty.
Analyzer configuration should be like that:
![screenshot from 2019-01-22 08-30-53](https://user-images.githubusercontent.com/2846609/51519192-8c1cdf80-1e20-11e9-8b74-c109d995e5cf.png)
