### ISSUE TITLE
New Analyzer: Cisco Umbrella Reporting

### ISSUE THREAD

**Issue by arnydo** [TheHive-Project/Cortex-Analyzers#385]
### Request Type
Analyzer

### Description
Analyzer will pull latest data from an organization's Umbrella instance via [Reporting API](https://docs.umbrella.com/umbrella-api/docs/overview) and provide:

- Recent Hits (True/False)
- Category
- Last Action (ALLOW/BLOCK)
- ?

### Possible Solutions
I'm working on the creation of the analyzer.

**Comment by nadouani** [comment]
PR accepted
