### ISSUE TITLE
Improvement: Eml_Parser Analyzer & Template

### ISSUE THREAD

**Issue by arnydo** [TheHive-Project/Cortex-Analyzers#394]
### Request Type
Analyzer Improvement

### Work Environment
N/A

### Description
Adjust handling of email headers. Provide cleaner report to display headers within a formatted table rather than one text string.

### Possible Solutions
Change result['headers'] from a list to a dict and display in a table.

### Complementary information
Pull request made #393

**Comment by nadouani** [comment]
Fixed by PR #393
