### ISSUE TITLE
Analyzer Feature: URLScan.io "Scan" Service

### ISSUE THREAD

**Issue by arnydo** [TheHive-Project/Cortex-Analyzers#405]
# Add "Scan" service to  URLScan.io analyzer

### Request Type
Feature

### Description
[WIP](https://github.com/arnydo/Cortex-Analyzers/tree/feature/urlscan_scan/analyzers/Urlscan.io)

**Comment by chelmzy** [comment]
What is the status of this analyzer?

**Comment by arnydo** [comment]
Dropped the ball on this one. I am working on rebuilding my TheHive instance but the latest Docker images seem to be giving some headache. Once back up and running I will tackle this analyzer.

**Comment by garanews** [comment]
Hi @arnydo any news about this?

**Comment by arnydo** [comment]
Hey @garanews  I still have not had the time to get back into this. I apologize for the delay.

**Comment by garanews** [comment]
Hello @arnydo , I see you have some code on your fork, need some help to complete it?

**Comment by arnydo** [comment]
@garanews if you want to assist feel free! I am sure others would benefit from this analyzer and I don't want to hold up the progress if others want to help complete it.

**Comment by dadokkio** [comment]
I'm working on the submit/result feature starting from your code. 
It's working.. I just need to understand which information are useful on the template.

**Comment by garanews** [comment]
Available in next 2.6.0
