### ISSUE TITLE
Restrict UnshortenLink usage to urls without IPs and/or ports

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/Cortex-Analyzers#413]
### Request Type
Bug

### Description
For security reasons, the UnshortenLink analyser have to disabled analysing urls using IPs or ports to disallow port scanning. Current version produces results that give a way to know if a given port is open or closed.

**Comment by 3c7** [comment]
Ref ea317b4644d0725fdb628fad790bdfadc04ab0a7
