### ISSUE TITLE
Crowdstrike Falcon Responder

### ISSUE THREAD

**Issue by saadkadhi** [TheHive-Project/Cortex-Analyzers#423]
### Request Type
Responder

### Work Environment
N/A

### Description
Provide a [Crowdstrike Falcon](
https://www.crowdstrike.com/blog/tech-center/import-iocs-crowdstrike-falcon-host-platform-via-api/) Responder.

### Complementary information
PR #421 has been submitted by @ag-michael. The new responder should be included in Cortex-Analyzers 1.16.0.

**Comment by ag-michael** [comment]
@saadkadhi I've added the changes requested and tidy'd up the regex a bit to match URLs that don't begin with a scheme.

**Comment by jeromeleonard** [comment]
merged #421
