### ISSUE TITLE
[Bug] TheHive isn't showing error messages from responders

### ISSUE THREAD

**Issue by mgabriel-silva** [TheHive-Project/Cortex-Analyzers#429]
**Describe the bug**
TheHive isn't showing error messages from responders.
I've tried with Mailer and a responder I created. Both of them doesn't show error messages.

**To Reproduce**
1. Use any responder that's going to fail. May be Mailer without mails in the observables ou wrongly configurated.
1. The responder will fail, but there's no message in the details button (magnifier glass).

**Possible solutions**
In case of error it should show the "errorMessage" instead of "message" of the response json

**Comment by Kamforka** [comment]
+1 for this one.

Is there any official workaround for this issue, or in the meantime we should just use the `message` for communicating responder alerts to TheHive?

**Comment by jeromeleonard** [comment]
Probably related to https://github.com/TheHive-Project/Cortex/issues/243

**Comment by nadouani** [comment]
Sorry guys, I'm just discovering this issue that should be fixed in TheHive but it's filled under cortex-analyzers repo, so it was not spotted

**Comment by garanews** [comment]
Fixed with https://github.com/TheHive-Project/TheHive/issues/962
