### ISSUE TITLE
[FR] Spamhaus DBL Analyzer

### ISSUE THREAD

**Issue by 3c7** [TheHive-Project/Cortex-Analyzers#436]
The Spamhaus Domain Block List (DBL) provides information about domain reputation:

- https://www.spamhaus.org/dbl/
- https://www.spamhaus.org/faq/section/Spamhaus%20DBL#291

This could be a good new analyzer. :)

**Comment by weslambert** [comment]
I can grab this if nobody is working on it.

Thanks,
Wes

**Comment by 3c7** [comment]
Hey @weslambert, that would be great!

**Comment by weslambert** [comment]
PR submitted: https://github.com/TheHive-Project/Cortex-Analyzers/pull/585
