### ISSUE TITLE
Maltiverse Analyzer

### ISSUE THREAD

**Issue by ottimo** [TheHive-Project/Cortex-Analyzers#440]
### Request Type
Analyzer

### Work Environment
N/A

### Description
A simple analyzer that uses Maltiverse API to get information about IP URL Domain and Hash.
https://maltiverse.com/

The API references are here:
https://app.swaggerhub.com/apis-docs/maltiverse/api/1.0.0

**Comment by ottimo** [comment]
I already start to develop it, I finished the client on cortex side.
I have to create the report on the hive side

**Comment by remiallain** [comment]
Hello @ottimo i've also developed a Maltiverse Analyzer:

[https://github.com/Cyberprotect/Cortex-Analyzers/commit/f8cc290e2691a77135b6f429b25d7fded5aa361d](https://github.com/Cyberprotect/Cortex-Analyzers/commit/f8cc290e2691a77135b6f429b25d7fded5aa361d)

If you want, we can combine our work :)

**Comment by ottimo** [comment]
I create the PR to add all my code #448
