### ISSUE TITLE
[Bug] Umbrella_Report_1_0 analyzer returning Invalid output

### ISSUE THREAD

**Issue by Tibap** [TheHive-Project/Cortex-Analyzers#459]
**Describe the bug**
Running the Umbrella_Report_1_0 analyzer returns the error message: "Invalid output\n".

**To Reproduce**
1. enable analyzer with your API key, secret and organization ID
2. Run the analyzer on the google.com domain from the Cortex UI
3. Wait for result

**Expected behavior**
Cortex displays output from the analyzer.

**Complementary information**
Querying results from the API using a browser with the same API key and secret works well. Output looks like valid json.

Other analyzers work well.

**Work environment**
 - Client OS: Windows 10
- Server OS: Debian 9
 - Browse type and version:
- Cortex version: 2.1.3-1
 - Cortex Analyzername: Umbrella_Report_1_0 
- Cortex Analyzer/Responder version: 1.0

**Comment by tnvo** [comment]
Also running into the same problem:
```
{
  "errorMessage": "Invalid output\n",
  "input": null,
  "success": false
}
```

**Comment by Tibap** [comment]
Has been resolved with last version of analyzers. Closing.
