### ISSUE TITLE
[Bug] Malwares_GetReport_1_0

### ISSUE THREAD

**Issue by 1623664** [TheHive-Project/Cortex-Analyzers#470]
Invalid output
Traceback (most recent call last):
  File "Malwares/malwares.py", line 163, in <module>
    MalwaresAnalyzer().run()
  File "Malwares/malwares.py", line 146, in run
    hash = hashlib.sha256(open(filepath, 'r').read()).hexdigest();
TypeError: Unicode-objects must be encoded before hashing

**Comment by nadouani** [comment]
Hello, can you please provide an example of observable that produces this error? 

Thanks

**Comment by 1623664** [comment]
sorry for so long answer. This happens every time you check the files. Hash is checked without errors.

**Comment by gl4ssiest** [comment]
Can confirm it: 
Invalid output

  _File "Malwares/malwares.py", line 163, in <module>
    MalwaresAnalyzer().run()
  File "Malwares/malwares.py", line 146, in run
    hash = hashlib.sha256(open(filepath, 'r').read()).hexdigest();
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte_
