### ISSUE TITLE
[FR] Analyzer for PaloAltoNetworks Autofocus service

### ISSUE THREAD

**Issue by amr-cossi** [TheHive-Project/Cortex-Analyzers#472]
**Feature description**
An API is available for the commercial service Autofocus provided by PaloAltoNetworks. This new analyzer will handle: 

- the export of a full analysis for one sample
- the research for samples linked to specific IOCs
- the research for samples based on a complex JSON query

**Describe the solution you'd like**
A first version of this analyzer has been written and submitted. TheHive templates have not been provided yet and some help is wanted for this part.

**Comment by nadouani** [comment]
Hello @amr-cossi how can we help to produce the templates?

**Comment by amr-cossi** [comment]
As I currently don't use The Hive, it's hard for me to design/produce/test templates.
I could produce fake result data for somebody else to create relevant ones.

Also, this Analyzer would benefit from this feature as the API is rate limited : https://github.com/TheHive-Project/Cortex/issues/164
