### ISSUE TITLE
[Bug] IBM X-Force Analyzer adds an extra slash which prevents it from running correctly

### ISSUE THREAD

**Issue by saadkadhi** [TheHive-Project/Cortex-Analyzers#487]
**Describe the bug**
As [originally reported](TheHive-Project/Cortex#84) by @csoc49 in the Cortex repository:

```
Hy,

we have a problem by connecting to the IBM X-Force API.
We always get a 401 API error.

We use these URL https://api.xforce.ibmcloud.com/ and take our API-Key and pwd in the Cortex configuration. Is there anybody with an idea??

:-/
```

**Complementary information**
@ssstonebraker reported the following:
> Hey i figured out how to fix this. I had the same problem and spent a couple hours figuring it out

> I kept receiving an "API error" when attempting to run TheHive Project Cortex Analyzer for IBM Xforce.

> There is currently a bug that is adding an extra / with every request.

> To fix this issue you need to modify this file:

`/opt/Cortex-Analyzers/analyzers/IBMXForce/ibmxforce_lookup.py`

> Command to fix the problem:

`perl -pi -e 's|%s/|%s|g' /opt/Cortex-Analyzers/analyzers/IBMXForce/ibmxforce_lookup.py`

> source:

https://brakertech.com/thehive-project-cortex-ibm-xforce-analyzer-is-not-working/

**Comment by ayounes2024** [comment]
hi team, i run the command but still issue exist
