### ISSUE TITLE
[Misc] Remove Cymon analyzer

### ISSUE THREAD

**Issue by ninoseki** [TheHive-Project/Cortex-Analyzers#489]
[Cymon](https://cymon.io) is is no longer maintained.

* Ref: https://twitter.com/royfire/status/1133702437892743168

So, unfortunately, the Cymon analyzer doesn't work now. 
I think it's good to remove that one from the analyzers.

**Comment by jeromeleonard** [comment]
oops, sorry, removed/pushed it before seeing your PR. Thx.
