### ISSUE TITLE
[Bug] Fortiguard: Category parsing does not handle "-"

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/Cortex-Analyzers#493]
**Describe the bug**
Categories such as "Web-based Applications" or "Web-based Email" are not properly pared and identified by the Fortiguard_URLCategory analyzer.

**To Reproduce**
1. execute `./urlcategory.py <<< '{"data":"http://trello.com","dataType":"url"}'`

result is:

```json
{
  "artifacts": [],
  "full": {
    "category": "Web"
  },
  "success": true,
  "summary": {
    "taxonomies": [
      {
        "predicate": "URLCat",
        "namespace": "Fortiguard",
        "value": "Web",
        "level": "info"
      }
    ]
  }
}
```

**Expected behavior**

The result should be:

```json
{
  "artifacts": [],
  "full": {
    "category": "Web-based Applications"
  },
  "success": true,
  "summary": {
    "taxonomies": [
      {
        "predicate": "URLCat",
        "namespace": "Fortiguard",
        "value": "Web-based Applications",
        "level": "info"
      }
    ]
  }
}
```

**Work environment**
- Server OS: Debian stretch
- Cortex version: N/A
 - Cortex Analyzer/Responder name: Fortiguard_URLCategory
- Cortex Analyzer/Responder version: 2.1

**Possible solutions**
* use regex `[-\w\s]+` instead of `[\w\s]+` to parse URL category from the API response

**Comment by jeromeleonard** [comment]
fixed by #494
