### ISSUE TITLE
Intezer Community analyzer

### ISSUE THREAD

**Issue by mlodic** [TheHive-Project/Cortex-Analyzers#504]
### Request Type
Analyzer

### Description
IntezerCommunity API to analyze possible malicious files and retrieve the result of the analysis.
https://analyze.intezer.com/api/docs/documentation#get-analysesanalysis-id
10 samples/day is free.

### Possible Solutions
I'll start to work on that as soon as I can.

**Comment by garanews** [comment]
Will be available in next 2.6.0
