### ISSUE TITLE
Invalid requirements in responder FalconCustomIOC requirements.txt

### ISSUE THREAD

**Issue by steoleary** [TheHive-Project/Cortex-Analyzers#509]
# Invalid requirements in FalconCustomIOC requirements.txt

### Request Type
Bug 

### Work Environment
N/A

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| Cortex Analyzer Name      | FalconCustomIOC
| Cortex Analyzer Version   | 1.0
| Cortex Version            | 3.0.0-RC3

### Description
When installing the requirements for the analyzers on ubuntu 18.04 you get an error from pip like below:

 ERROR: Could not find a version that satisfies the requirement traceback (from -r /opt/Cortex-Analyzers/responders/FalconCustomIOC/requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for traceback (from -r /opt/Cortex-Analyzers/responders/FalconCustomIOC/requirements.txt (line 2))

Looking at the requirements.txt it contains:
json
re
requests
traceback

Of these, only requests seems to work correctly

### Steps to Reproduce
Install cortex on Ubuntu 18.04
Clone analyzers into /opt/Cortex-Analyzers

Install the requirements using:
for I in $(find /opt/Cortex-Analyzers -name 'requirements.txt'); do sudo -H pip2 install -U -r $I; done && \
for I in $(find /opt/Cortex-Analyzers -name 'requirements.txt'); do sudo -H pip3 install -U -r $I || true; done

Observe the errors regarding json, re and traceback

**Comment by github-pba** [comment]
You can safely ignore this error.

The requirements.txt lists `json` and `re` as required modules (which is true), but these are python builtins.

I will update the requirements and send a pull request for this.

**Comment by garanews** [comment]
Solved with https://github.com/TheHive-Project/Cortex-Analyzers/pull/517
