### ISSUE TITLE
Talos Analyzer No Longer Works

### ISSUE THREAD

**Issue by colin-stubbs** [TheHive-Project/Cortex-Analyzers#521]
**Describe the bug**
Talos now uses rolling cookies on their API, requests to API without a valid cookie do not work.

**To Reproduce**
Use existing analyzer, it is no workies.

**Expected behavior**
Works.

**Complementary information**
n/a

**Work environment**
 Latest

**Possible solutions**
Need to use requests.Session() against https://talosintelligence.com/reputation_center/lookup?search=IPADDRESS
This obtains cookies, then subsequent requests to API work

**Additional context**
nOpe.

**Comment by robertnixon2003** [comment]
Lets get this merged. I use this one alot.
