### ISSUE TITLE
[Bug] HIBP Analyser no longer works

### ISSUE THREAD

**Issue by znb** [TheHive-Project/Cortex-Analyzers#524]
**Describe the bug**
On July 2019 they updated the API to use [authentication](https://haveibeenpwned.com/API/v3#Authorisation). All queries will now fail.

**To Reproduce**
1. Run the HIBP analyser 
1. ???
1. Profit
1. Nope.

**Expected behavior**
A valid response from the API. 

**Possible solutions**
We need to update the analyser to take an API key in the configuration. 

There will be changes to the analyser code:
1. Change to the v3 API
1. Adding in authentication header

**Comment by jeromeleonard** [comment]
hello, 

thanks to @jonashergenhahn for the PR https://github.com/TheHive-Project/Cortex-Analyzers/pull/525 that should fix this. The new version of this analyzer has been merged in develop branch. As API subscription are temporary disabled I have not been able to test. Please make some test on your side and tell us if everything is fine.
