### ISSUE TITLE
[Bug?] Template reports problem with custom analyzers

### ISSUE THREAD

**Issue by b00lpy** [TheHive-Project/Cortex-Analyzers#526]
Sorry if I don't fill all the preliminar table.
It's a simple Analyzer running inside a Cortex 3.0.0-RC3 container from a Ubuntu 18.04.

It can give me the raw output. I filled the templates copying the code for **Short Template** from the actual guide provided from TheHive Project here: https://github.com/TheHive-Project/CortexDocs/blob/master/api/how-to-create-an-analyzer.md#report-templates

But doesn't work. And can't see any tag added to the observables.

Any suggestions?

**Comment by nadouani** [comment]
Hello, I would say this is not a bug, it's something related to your own analyzer template.

Please ask the question on the user-group and provide more details about
- what is not working
- a sample of analysis report

Thanks

**Comment by nadouani** [comment]
I could help you here, but it's not really where we should make it
