### ISSUE TITLE
[Bug] Can't Remove an Analyzer

### ISSUE THREAD

**Issue by b00lpy** [TheHive-Project/Cortex-Analyzers#528]
I'm running Cortex through Docker Container using the official image provided:
Cortex  -  3.0.0-RC3
Elastic4Play  -  1.11.3
Play  -  2.6.23
Elastic4s  -  6.5.1
ElasticSearch client  -  6.5.2

I added a custom analyzer by mounting the root directory inside the `/opt/Cortex-Analyzers/analyzers`, but accidentally i mounted the wrong one. The problem is that now Cortex keeps showing me the name of this one even if I didn't mount the volume, and obviously it crashes because the executable doesn't actually exists.

The question is, how can I permanently remove from Cortex everything about this Analyzer?

**Comment by RtKelleher** [comment]
Not sure the specific reason [Cortex isn't removing defunct analyzers](https://github.com/TheHive-Project/Cortex/issues/234), but I found that removing the first entry in ElasticSearch for the analyzer will remove the entry in Cortex.

**Comment by jeromeleonard** [comment]
Did you "refresh" the analyzers list in Cortex (button in the Available analyzers tab) ?

**Comment by nadouani** [comment]
This is in fact a Cortex related bug (https://github.com/TheHive-Project/Cortex/issues/234).

Sadly, The invalid analyzer have to be removed by hand from ElasticSearch.
