### ISSUE TITLE
[Bug] Cuckoo Sandbox 2.0.7

### ISSUE THREAD

**Issue by 1earch** [TheHive-Project/Cortex-Analyzers#544]
**Describe the bug**
Since Cuckoo 2.0.7 update, the analyzer isn't working.

**To Reproduce**
1. Fresh install of Cuckoo 2.0.7
1. Fresh install of Cortex & Cortex-Analyzers

**Expected behavior**
Cortex analyzer contacting Cuckoo.

**Complementary information**
In Cuckoo 2.0.7, the developers secured the API with a token which must be sent in a HTML header (`Bearer`).

**Possible solutions**
PR #514

**Comment by 3c7** [comment]
Fix merged to develop.
