### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/Cortex-Analyzers#552]
**Describe the bug**
ProofPoint analyzer is not found when called. 

**To Reproduce**
1. Configure the ProofPoint Analyzer in Cortex
1. Run a URL or other IOC against it
1. then I get this:

```
[INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-16 - GET /api/analyzer/ProofPoint_Lookup_1_0 returned 404
```

**Expected behavior**
Return results after successfully running the analyzer. 

**Complementary information**
If applicable, add screenshots and any additional information that might help explain your problem.

**Comment by robertnixon2003** [comment]
![image](https://user-images.githubusercontent.com/20773170/67299216-5a719b80-f4ba-11e9-9d75-40becbda214d.png)

**Comment by robertnixon2003** [comment]
It is there and enabled. But when you pull all the analyzers if is not in the list. 

curl --noproxy "*" -H 'Authorization: Bearer ****************************' 'https://*****************:9000/api/analyzer/ProofPoint_Lookup_1_0'
{"type":"NotFoundError","message":"worker ProofPoint_Lookup_1_0 not found"}

**Comment by jeromeleonard** [comment]
Hi  @robertnixon2003,  this is due to the missing 'x' permissions on `proofpoint_lookup.py`file. Add it and refresh analyzers  in the UI. I fix it.
