### ISSUE TITLE
[Bug] Mailer 1_0

### ISSUE THREAD

**Issue by KRUXLEX** [TheHive-Project/Cortex-Analyzers#573]
**Describe the bug**
Unexpected end-of-input within/between Object entries\n at [Source: (sun.nio.ch.ChannelInputStream);

**To Reproduce**
add ascii characters other than standard characters like: ś ć ń

**Expected behavior**
Fix

**Complementary information**
`"errorMessage": "Unexpected end-of-input within/between Object entries\n at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 1045]",`

**Work environment**
 - Client OS: Debian
- Server OS: Centos 
 - Browse type and version: N/D
- Cortex version: 3.0.0-1
 - Cortex Analyzer/Responder name: Mailer
- Cortex Analyzer/Responder version: 1_0

**Comment by dadokkio** [comment]
Hi @KRUXLEX ,
I made a few modification in this pull #717 . Can you please check if this fixes the issue?

**Comment by KRUXLEX** [comment]
> 
> 
> Hi @KRUXLEX ,
> I made a few modification in this pull #717 . Can you please check if this fixes the issue?

I will try in this week.

**Comment by dadokkio** [comment]
@KRUXLEX any update?

**Comment by KRUXLEX** [comment]
Hi i haven't time to check it. Please reopen issue, I will check it in until Friday.
