### ISSUE TITLE
[FR] Team Cymru Malware Hash Registry Analyzer

### ISSUE THREAD

**Issue by weslambert** [TheHive-Project/Cortex-Analyzers#576]
I've developed an analyzer to submit a file hash to Team Cymru's Malware Hash Registry and return an evaluation (detection percentage). Will submit a PR soon.

**Comment by weslambert** [comment]
PR: https://github.com/TheHive-Project/Cortex-Analyzers/pull/580

**Comment by nadouani** [comment]
PR has been merged.
