### ISSUE TITLE
Add Wazuh Responder

### ISSUE THREAD

**Issue by weslambert** [TheHive-Project/Cortex-Analyzers#578]
I've created a responder to initiate Wazuh Active Response against a particular IP, with the first iteration being a firewall drop via the Wazuh agent. Will submit PR soon.

**Comment by weslambert** [comment]
PR: https://github.com/TheHive-Project/Cortex-Analyzers/pull/582

**Comment by nadouani** [comment]
Hello @weslambert The PR has been merged. 

Is it possible to add a doc PR for https://github.com/TheHive-Project/CortexDocs/blob/master/analyzer_requirements.md

Cheers

**Comment by weslambert** [comment]
Will do, @nadouani !

**Comment by weslambert** [comment]
PR for docs: https://github.com/TheHive-Project/CortexDocs/pull/59
