### ISSUE TITLE
[FR] Velociraptor Analyzer/Responder

### ISSUE THREAD

**Issue by weslambert** [TheHive-Project/Cortex-Analyzers#579]
I've begun creating a Velociraptor responder to run flows based on certain conditions.  This may also be created as an analyzer to perform analysis and gather certain details.  Will submit PR soon.

**Comment by garanews** [comment]
Hi @weslambert are you still on Velociraptor  responder/analyzer ?

**Comment by weslambert** [comment]
Yes, I will be putting my PR up soon.

**Comment by garanews** [comment]
Any news?

**Comment by weslambert** [comment]
Sorry, finishing this up got put in my backlog -- I've just got to tighten up a few things and make some tweaks and will have something to you guys.

**Comment by weslambert** [comment]
Just wanted to follow up on this -- should have something to you by the end of the week 😉.  Having to make some updates due to updates with the tool itself.

**Comment by weslambert** [comment]
https://github.com/TheHive-Project/Cortex-Analyzers/pull/803

**Comment by garanews** [comment]
added in 2.9.0
