### ISSUE TITLE
[Bug] All Onyphe analyzer return "Invalid output"

### ISSUE THREAD

**Issue by icepaule** [TheHive-Project/Cortex-Analyzers#591]
**Describe the bug**
I just pulled that latest version an tested the 4 Onyphe analyzers.
They all come back with:
{
  "errorMessage": "Invalid output\n",
  "input": null,
  "success": false
}

**To Reproduce**
call any Onyphe analyzer with an IP

**Expected behavior**
A valid response

**Complementary information**
A great and fantastic tool. Please keep up this fantastic work ..!!!!   :-)

**Work environment**
- Client OS: Windows 10
- Server OS: Ubuntu 18.04
- Browse type and version: Chrome (latest)
- Cortex version: 2.1.3-1
- Cortex Analyzer/Responder name: Onyphe_Forward_1_0
- Cortex Analyzer/Responder version: 1.0
- Cortex Analyzer/Responder name: Onyphe_Ports_1_0
- Cortex Analyzer/Responder version: 1.0
- Cortex Analyzer/Responder name: Onyphe_Reverse_1_0
- Cortex Analyzer/Responder version: 1.0
- Cortex Analyzer/Responder name: Onyphe_Threats_1_0
- Cortex Analyzer/Responder version: 1.0

**Possible solutions**
n.a.

**Additional context**
n.a.

**Comment by garanews** [comment]
Hello,
I just tried all 4 analyzers and everything is ok:
![image](https://user-images.githubusercontent.com/16938405/72715596-12255080-3b71-11ea-88eb-0d14527a5881.png)
![image](https://user-images.githubusercontent.com/16938405/72715638-2406f380-3b71-11ea-87eb-46124dc5270b.png)
![image](https://user-images.githubusercontent.com/16938405/72715656-2cf7c500-3b71-11ea-978c-4c953db33ba5.png)


I can receive this error
{
  "input": null,
  "success": false,
  "errorMessage": "no output",
  "artifacts": []
} 

If I try to analyze an ip written in wrong way, such as add it with [.]
Not able to receive "Invalid output"
Can you give me more info to reproduce issue?

**Comment by jeromeleonard** [comment]
Also made some test, with and without docker, from TheHive and directly into Cortex, with fanged real IP address and also unfanged. Also tried with bad IP address. Never managed to get this output. 
@icepaule  last version of Cortex is 3.0.1, could you please try with this version ?

**Comment by nadouani** [comment]
@garanews I thing we should fix the milestone of this issue

**Comment by garanews** [comment]
Hi @icepaule are you still experiencing this error?

**Comment by dadokkio** [comment]
We can consider this issue closed. If you still have this issues please reopen this issue adding more information.
