### ISSUE TITLE
[Bug] Worker cannot be run

### ISSUE THREAD

**Issue by miguelfaldutti87** [TheHive-Project/Cortex-Analyzers#595]
**Describe the bug**
When I try to analyze a file using HybridAnalysis Analyzer I get this error:  "errorMessage": "Worker cannot be run",.

**To Reproduce**
I go to "Analyzers" and select "Run" on HybridAnalysis Analyzer. Then I choose a file and then accept.
I get a pop messages that says that the process started okay and after a couple of seconds I get the error message.

**Work environment**
- Server OS: Ubuntu 18.04
Cortex 3.0.1-1
Elastic4Play 1.11.5
Play 2.6.23
Elastic 4s6.5.1
ElasticSearch clien t6.5.2

**Comment by jeromeleonard** [comment]
Could you please copy the error message you get in the job history page of Cortex ? 
Thanks.

**Comment by miguelfaldutti87** [comment]
Yes. I get this:

"errorMessage": "Worker cannot be run".

**Comment by jeromeleonard** [comment]
are you trying to use Docker? 
In this case maybe your cortex user in not autorise to access docker.

**Comment by miguelfaldutti87** [comment]
Nop, I'm running all on the same Virtual Machine. I'm not using docker.

**Comment by jeromeleonard** [comment]
Please, provide us more details : 
- related logs from cortex  from `/var/log/cortex/application.log`
- `/opt/Cortex-Analyzers/analyzers/HybridAnalysis/HybridAnalysis_analyzer.py` is executable  and Cortex user has permissions to do that ?
-  try it with this in the Cortex configuration file: 

````
[..]
job {
  timeout = 30 minutes
  runners = [process]
}
## ANALYZERS
# 
[..]
```

**Comment by dadokkio** [comment]
can this issue be related https://github.com/TheHive-Project/Cortex/issues/248 ??

**Comment by jeromeleonard** [comment]
without reply we close this issue. Please, tell us if the problem still exist and we reopen it.

**Comment by niomictomi** [comment]
the problem still exist, Please help me !
