### ISSUE TITLE
[FR] CyberChef Analyzer

### ISSUE THREAD

**Issue by weslambert** [TheHive-Project/Cortex-Analyzers#600]
I've created an analyzer to automatically convert data via [CyberChef server](https://github.com/gchq/CyberChef-server).

This analyzer includes data transformations for Base64, Hex,  and [CharCode](https://github.com/mattnotmax/cyberchef-recipes#recipe-3---from-charcode) -- it can be expanded in the future, but I figured this would be a good first start.

PR here: https://github.com/TheHive-Project/Cortex-Analyzers/pull/599

**Comment by dadokkio** [comment]
Hi, I'm trying to run your analyzer with cyberchef-server docker but it's not working.
The response from the server is something like:
`{"value":[99,105,97,111],"type":"byteArray"}`
and your code is returning error:
```
Traceback (most recent call last):
  File "test_cyb.py", line 15, in <module>
    output_data = str(output_data + str(chr(int(i))))
ValueError: invalid literal for int() with base 10: '{"value":[99'
```
I'm not sure if this depends from a different release of the cyberchef-server but I had to change your code to something like:

```
r = requests.post(url.strip('/') + '/bake', headers=headers, data=json.dumps(data))
output_data = "".join([chr(x) for x in r.json().get('value', [])])
self.report({ 'input_data': observable, 'output_data': output_data })

```

**Comment by weslambert** [comment]
Thanks for reporting @dadokkio  -- I'll look into this.

**Comment by weslambert** [comment]
So, it looks like, for some reason or another, as you pointed out, the code I had previously was no longer working.  I've updated per the suggestion and it seems to be working okay now:

https://github.com/TheHive-Project/Cortex-Analyzers/pull/697/commits/427a9a7182738ffb94bba8f555540ddc6fc8673a

**Comment by weslambert** [comment]
Awesome, thanks @jeromeleonard !
