### ISSUE TITLE
[Bug] DNSDB Analyzer Python 3 incompatability

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/Cortex-Analyzers#613]
**Describe the bug**
Upgrading DNSDB's shebang to `python3` wasn't enough to get it working... There's a lot of python2 quirks still left in the source code.

**Notes:**
While it would be best practice to isolate this fix to a single PR, I'm debugging this using tools I've created as part of [my other PR](https://github.com/TheHive-Project/Cortex-Analyzers/pull/607) and will be bundling this fix in with that.

**Comment by milesflo** [comment]
Potential fix at commit: https://github.com/TheHive-Project/Cortex-Analyzers/pull/607/commits/b64ca1b32ff3375dbad29c5e0b25faba743a3a31

**Comment by jeromeleonard** [comment]
Hi, 

thank for seeing that, and the fix submitted. I am about to release a hot fix/2.4.1. Could you please submit a PR with just the fix for DNSDB so that I can merge it in it ? 

Regards,

**Comment by milesflo** [comment]
@jeromeleonard  https://github.com/TheHive-Project/Cortex-Analyzers/pull/696

**Comment by garanews** [comment]
fixed in 2.7.0
