### ISSUE TITLE
[Bug] Hippocampe using urllib2

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/Cortex-Analyzers#615]
**Describe the bug**
The Hippocampe Analyzer is still using `urllib2`, a hang-on from when it was originally written for python 3

**Possible solutions**
Upgrade to `urllib3`. Their APIs are basically identical so it's not too difficult.

**Additional context**
Addressing in https://github.com/TheHive-Project/Cortex-Analyzers/pull/607

**Comment by milesflo** [comment]
Fixed: https://github.com/TheHive-Project/Cortex-Analyzers/pull/607/commits/41069e7084c457616d04562b6d012c50783285d9

**Comment by jeromeleonard** [comment]
Could you please submit a dedicated PR for this update ? We will then be able to release it a the future version. 

Thanks.

**Comment by milesflo** [comment]
@jeromeleonard Here you go: https://github.com/TheHive-Project/Cortex-Analyzers/pull/667 Still has the Dockerfile but is far leaner.
