### ISSUE TITLE
[Bug] abuselpdb stop stupport APIv1

### ISSUE THREAD

**Issue by KRUXLEX** [TheHive-Project/Cortex-Analyzers#618]
**Describe the bug**
Officially AbuselPDB stop support his own APIv1. They start working on APIv2.

**To Reproduce**
Run Analyzer normlany

**Expected behavior**
Working

**Complementary information**
```
{
  "values": [
    {
      "detail": "The APIv1 check endpoint has sunset. Please migrate to the APIv2 version of this endpoint. You will need a new API key.",
      "links": {
        "related": "https://docs.abuseipdb.com/#check-endpoint"
      },
      "status": 404
    }
  ]
}
```

**Work environment**
 - Client OS: Debian9
- Server OS: Centos8
 - Browse type and version: Mozzilla
- Cortex version: 3.4.0-1
 - Cortex Analyzer/Responder name: AbuseIPDB_1_0
- Cortex Analyzer/Responder version:AbuseIPDB

**Possible solutions**
Convert script to new varsion of API. Using a GET metod:
```
import requests
import json

# Defining the api-endpoint
url = 'https://api.abuseipdb.com/api/v2/check'

querystring = {
    'ipAddress': '118.25.6.39',
    'maxAgeInDays': '90'
}

headers = {
    'Accept': 'application/json',
    'Key': '$YOUR_API_KEY'
}

response = requests.request(method='GET', url=url, headers=headers, params=querystring)

# Formatted output
decodedResponse = json.loads(response.text)
print(json.dumps(decodedResponse, sort_keys=True, indent=4))
 
```

**Additional context**
nOpe

**Comment by dadokkio** [comment]
closed in 2.6.0
