### ISSUE TITLE
[Bug] Importing Templates of Analyzers in Hive

### ISSUE THREAD

**Issue by KRUXLEX** [TheHive-Project/Cortex-Analyzers#704]
**Describe the bug**
When I importing a templates to thehive, I haven't get any error, but templates don't import correctly (without his body)

**To Reproduce**
`zip -r thehive-templates.zip thehive-templates/`
![image](https://user-images.githubusercontent.com/22861005/75525305-ec148b00-5a0f-11ea-8e6e-ec5e66f1c634.png)
![image](https://user-images.githubusercontent.com/22861005/75525418-16fedf00-5a10-11ea-8177-13bc76cf4889.png)
![image](https://user-images.githubusercontent.com/22861005/75525443-1e25ed00-5a10-11ea-98f2-4c825a5c2d8f.png)
![image](https://user-images.githubusercontent.com/22861005/75525478-36960780-5a10-11ea-8386-baacb4fb2e13.png)
![image](https://user-images.githubusercontent.com/22861005/75525558-588f8a00-5a10-11ea-9c7d-72ffd3636625.png)
![image](https://user-images.githubusercontent.com/22861005/75525521-47467d80-5a10-11ea-8d0f-ce368a761466.png)

**Expected behavior**
Fix it, or tell how import it correctly

**Comment by garanews** [comment]
instead do:
`zip -r thehive-templates.zip thehive-templates/`
try:
`cd thehive-templates`
`zip -r thehive-templates.zip  *`

**Comment by KRUXLEX** [comment]
Working

**Comment by KRUXLEX** [comment]
Working!!!

**Comment by KRUXLEX** [comment]
Working!!!
