### ISSUE TITLE
New Analyzer: MalwareBazaar

### ISSUE THREAD

**Issue by garanews** [TheHive-Project/Cortex-Analyzers#722]
### What is MalwareBazaar?
MalwareBazaar collects known malicious malware sample, enriches them with additional intelligence and provides them back to the community - for free! Here are just some of the features of MalwareBazaar:

- Completely community driven and 100% free for commercial and non-commercial usage
- Vetted malware samples only. No benign files. No Adware/PUP/PUA
- Download as many malware samples you like
- Extensive API for automation
- Export of hashes
- Daily malware batches avilable for download
- Additional context about malware samples distributed via email by using spamtrap data
- Search for samples by malware family name, fuzzy hashing (like TLSH, imphash, etc) and tags

### Why MalwareBazaar?
As many IT-security researchers, I'm heavily using public available information (OSINT) for hunting down new cyber threats. OSINT is a great resource for this threat intelligence! However, I often get confronted with a simple but severe problem: malware samples referenced in blog posts, whitepaper or mentioned on social media like Twitter are usually not easily available. You need to register on gazillion different online anti-virus scanning engines, sandboxes or malware databases in order to finally obtain the malware sample you need for your analysis. And it is getting worse: Some of these platforms come with download restrictions (you can only download a specific number of malware samples per day), some other platforms are available for paying users only. This is a huge pain for me in my daily work, and I'm sure for many other IT-security researchers out there too.

I've therefore asked myself: why do I have to register on 35457 different platforms? And why should I pay for downloading malware samples?

This was the motivation for launching MalwareBazaar: A malware corpus where IT-security researchers can easily share malware samples with the community without hitting download restrictions all the time or having to pay expensive subscription fees.

### What's the difference to VirusTotal?
VirusTotal is a great resource for threat intel and hunting malware. Unlike MalwareBazaar, VirusTotal is also a multi anti-virus scanner that allows you to asses whether a certain file is malicious or benign. However, VirusTotal has a handful limitation:

- While you can upload as many files to VirusTotal as you want, downloading malware samples from VirusTotal is restricted to paying users only
- As of March 2020, only 1/3 of all uploaded files are detected by at least one AV-endinge (VirusTotal Statistics). So it appears that 2/3 of all uploaded samples are benign

MalwareBazaar follows a different approach:

- MalwareBazaar only tracks malware samples. No Adware (PUA/PUP). No benign files
- MalwareBazaar is not a multi antivirus scanning engine
- You can upload and download as many malware samples as you want
- It's completely free!

![image](https://user-images.githubusercontent.com/16938405/77180811-c0df0200-6aca-11ea-9ecc-d4f00f7052d4.png)

Sources:
https://abuse.ch/blog/introducing-malwarebazaar/
https://bazaar.abuse.ch/

**Comment by garanews** [comment]
available in 2.7.0

**Comment by Passimist** [comment]
Any chance for an update that lets us use this analyzer on files? (by calculating their hash or reading it from the observable)
