### ISSUE TITLE
[discussion] Mispwarninglist analyzer speed issue and proposed improvement 

### ISSUE THREAD

**Issue by dadokkio** [TheHive-Project/Cortex-Analyzers#731]
It happens that we run this analyzer on multiple osservable and then the server situation is something like:

![immagine](https://user-images.githubusercontent.com/355183/77639390-01220280-6f59-11ea-9ec7-95ecb285f047.png)

All the scripts runs for dozens of hours and nothing else can be run until they finish so we decided to change approach.
Our solution is to put everything on a postgres database and search it if enable. 
You still need to pull lists as usual and then with a script provided you can insert them on the database. The script provides also a simple validation in order to avoid entering invalid tld or wrong ip.

The results and template are very similar, the main difference is timing.

**Comment by garanews** [comment]
new version available in 2.7.0
