### ISSUE TITLE
[Bug] MaxMind

### ISSUE THREAD

**Issue by sychev-a-k** [TheHive-Project/Cortex-Analyzers#752]
**Describe the bug**
Error when I try to use Maxmind Analyzer from TheHive UI or Cortex UI
Unexpected end-of-input within/between Object entries at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 901]

i found similar isssue [https://github.com/TheHive-Project/Cortex-Analyzers/issues/573](url)

**To Reproduce**
add ascii characters other than standard characters

**Expected behavior**
Fix

**Complementary information**
When I try launch script from console - everything is work
![image](https://user-images.githubusercontent.com/29555052/79999936-2efd5700-84c5-11ea-8012-c1a33fbd19d7.png)

**Work environment**
 the latest versions of Thehive and Cortex in docker environment

**Comment by dadokkio** [comment]
related issue should be https://github.com/TheHive-Project/Cortex-Analyzers/issues/564 
Is the analyzer in your cortex running with python3?

**Comment by sychev-a-k** [comment]
I chanched to python3 and it worked. Thank you
But if other analyzer works only with python2.7? How can i support this?

**Comment by dadokkio** [comment]
There is a work in progress to make all the analyzers python3 compatible and only few are not working yet.
If you have both python versions on your machine the first row of any script will indicate which python release you must use: https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take
