### ISSUE TITLE
ThreatResponse analyzer fails

### ISSUE THREAD

**Issue by maugertg** [TheHive-Project/Cortex-Analyzers#759]
**Describe the bug**
ThreatResponse analyzer fails with a stack trace

<img width="889" alt="threatresponse_analyzer_failure" src="https://user-images.githubusercontent.com/5721268/81313271-aac6da00-9055-11ea-8d40-9ea7022c337e.png">

**To Reproduce**
1. Enable analyzer
2. Run analyzer

**Expected behavior**
The analyzer to not fail and return results

**Complementary information**
Threat Response v1.47 pushed a breaking change to the `/observe/observables` API the `module_type` property has been removed from the response

```json
    {
      "module": "AMP File Reputation",
      "module_instance_id": "ddcf41a2-3ecb-43e8-b5b2-0e36ad2e16f3",
      "module_type_id": "1898d0e8-45f7-550d-8ab5-915f064426dd",
      "data": {
```

**Work environment**
 - Client OS: Any
- Server OS: Any
 - Browse type and version: Any
- Cortex version: Any
 - Cortex Analyzer/Responder name: ThreatResponse
- Cortex Analyzer/Responder version: 1.0

**Possible solutions**
Remove lines using `module_type`:
https://github.com/TheHive-Project/Cortex-Analyzers/blob/master/analyzers/ThreatResponse/ThreatResponse.py#L85
https://github.com/TheHive-Project/Cortex-Analyzers/blob/master/analyzers/ThreatResponse/ThreatResponse.py#L100

Remove explicit check for `AMPInvestigateModule` module:
https://github.com/TheHive-Project/Cortex-Analyzers/blob/master/analyzers/ThreatResponse/ThreatResponse.py#L211

**Comment by LaZyDK** [comment]
I manually did the fixes described. Working as intended. :)
