### ISSUE TITLE
[FR] DNSDB analyzer - more limiter options

### ISSUE THREAD

**Issue by gpanayot87** [TheHive-Project/Cortex-Analyzers#770]
As of now, the DNSDB Community Edition API key access includes:

- Up to 500 queries/month
- Up to 25 queries/hour with 256 results per query

However we can only set one limiter type and not both.

If possible, an option to set both limiters should be implemented.

**Comment by dadokkio** [comment]
I think that this issue must be opened in cortex repo because it's a common settings and not something specific to an analyzer.
