### ISSUE TITLE
[Bug]Pulsedive analyzer doesn't work

### ISSUE THREAD

**Issue by NailBash** [TheHive-Project/Cortex-Analyzers#788]
Hello, everyone. I have problem with "Pulsedive_GetIndicator_1_0" analyzer. It can't take response from pulsedive. It fails with:
![изображение](https://user-images.githubusercontent.com/29750691/84257993-a5b2ea00-ab2f-11ea-829d-a81f8bd774d0.png)

API key should be correct, I check it 10 times. My cortex runs on Centos 7.

**Comment by dadokkio** [comment]
Hello, just tried the analyzer and everything is fine.
Looking the error it is a cortex problem, probably related to analysis timeout or connection issues.
If the problem is still present I suggest to open an issue in cortex repository to have a better answer.
