### ISSUE TITLE
Remove catalogs

### ISSUE THREAD

**Issue by jeromeleonard** [TheHive-Project/Cortex-Analyzers#789]
Catalogs are no longer generated and used in the github repository.

**Comment by ctr49** [comment]
Are there any implications from this change? We used to pull from git and then run update_catalogs.sh
Is no further command execution required anymore? I'd suggest to put this into the release notes too.

**Comment by jeromeleonard** [comment]
Hi,

they are now generated and upload automatically on our servers with Drone. We are using this image to do that: https://github.com/TheHive-Project/neurons-build-catalogs

for example `analyzers.json` can be found at https://download.thehive-project.org/analyzers.json
