### ISSUE TITLE
EML-Parser Requirements file missing pip requirement

### ISSUE THREAD

**Issue by edwardrixon** [TheHive-Project/Cortex-Analyzers#792]
# EML-Parser Requirements file missing pip requirement.

### Request Type
Bug

### Work Environment
N/A
### Description
Requirements.txt file on the analyser "EML parser" directory does not have iocextract as a pip requirement but this is required for the EML Parser to function.
### Steps to Reproduce
attempt to run EML parser on the cli via python3 parse.py and you run into a module not found error.

### Possible Solutions
Add iocextract to the requirements file for the analyser "EML Parser".

**Comment by dadokkio** [comment]
Hi, the ioc extraction has been added in release 2.7.0 and requirements are already satisfied for that release: https://github.com/TheHive-Project/Cortex-Analyzers/commit/99337a41eea6d10784a45c0c94e6aaebac4bbde7

Probably you have mixed old requirements with new analyzer code.

**Comment by edwardrixon** [comment]
ok thankyou very much I will close.

> Hi, the ioc extraction has been added in release 2.7.0 and requirements are already satisfied for that release: [99337a4](https://github.com/TheHive-Project/Cortex-Analyzers/commit/99337a41eea6d10784a45c0c94e6aaebac4bbde7)
> 
> Probably you have mixed old requirements with new analyzer code.
