### ISSUE TITLE
[Bug] IntezerCommunity Analyser: Permission denied

### ISSUE THREAD

**Issue by PlaceboRulez** [TheHive-Project/Cortex-Analyzers#801]
Describe the bug
The IntezerCommunity docker analyser errors out with:

 Intezer: /job: 1: /job: IntezerCommunity/intezer_community.py: Permission denied

Expected behavior
The analyser should submit the file for analysis to Intezer

Work environment
Client OS: Windows 10
Server OS: Ubuntu 20.04
Browse type and version: Chrome
Cortex version: 3.0.1-1
Cortex Analyzer/Responder name: IntezerCommunity
Cortex Analyzer/Responder version: 1.0

Possible solutions
Execute bit on intezer_community.py?

**Comment by jeromeleonard** [comment]
Several analyzers and responders do not have exec permission. This will be fixed in 2.8.1
