### ISSUE TITLE
[Bug] OTX analyser no requests module on line 4

### ISSUE THREAD

**Issue by asucrews** [TheHive-Project/Cortex-Analyzers#818]
**Describe the bug**
Analyzers is erroring out with below error using docker images.

{
  "errorMessage": "Traceback (most recent call last):\n  File \"OTXQuery/otxquery.py\", line 4, in <module>\n    import requests\nModuleNotFoundError: No module named 'requests'\n",
  "input": null,
  "success": false
}

**To Reproduce**
1. enable otx analyzer
2. run otx analyzer
3. get error

**Expected behavior**
Results from OTX

**Complementary information**
{
  "errorMessage": "Traceback (most recent call last):\n  File \"OTXQuery/otxquery.py\", line 4, in <module>\n    import requests\nModuleNotFoundError: No module named 'requests'\n",
  "input": null,
  "success": false
}

**Work environment**
 - Client OS: windows 10
- Server OS: ubuntu 20.04
 - Browse type and version: Version 83.0.4103.116 (Official Build) (64-bit)
- Cortex version:  3.0.1-1
 - Cortex Analyzer/Responder name: OTXQuery_2_0
- Cortex Analyzer/Responder version: 2.0

**Possible solutions**

**Additional context**
Works with Proccess runner, just not with docker runner

**Comment by dadokkio** [comment]
The requests module has been added to requirements 7 months ago. 
https://github.com/TheHive-Project/Cortex-Analyzers/commit/9ff4f1f1913018476dc6a50f8f8fb388ff80aaab
Are you using the latest available release?

**Comment by asucrews** [comment]
Yes Latest Release, this fresh install last night with the default application config to use docker.
when i disable docker and ran the analyzer non docker method it work.
@dadokkio Could the docker image be missing it?

**Comment by jeromeleonard** [comment]
@asucrews could you please confirm this is still note working on your side ? Just made a successful test.
here is the docker image info: 
```
cortexneurons/otxquery                 2                   930bf2f9f79d        2 months ago        942MB
```

**Comment by asucrews** [comment]
sorry for the delay, this my docker image

REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
cortexneurons/otxquery   devel               c3a6b2a93bb5        2 weeks ago         939MB

**Comment by dadokkio** [comment]
Just tested docker release on thehive4 image and the image for otxquery is the similar to Jerome one.
Not sure why you're pulling the devel image, in my case the link used to download analyzer in "cortex/application.conf" is https://dl.bintray.com/thehive-project/cortexneurons/analyzers.json

**Comment by dadokkio** [comment]
Closing since no update.
