### ISSUE TITLE
[Bug]Robtex api end point are no longer valid?

### ISSUE THREAD

**Issue by asucrews** [TheHive-Project/Cortex-Analyzers#821]
**Describe the bug**
It looks like Robtex API endpint no longer valid or down for good.  I currently get 523 error form https://freeapi.robtex.com/.  Is there a process for deprecating a Analyzers

**To Reproduce**
1. Enable Robtex Analyzer
1. Run any mode
1. Get error rusults

**Expected behavior**
Results returned from Robtex

**Complementary information**
If applicable, add screenshots and any additional information that might help explain your problem.

**Work environment**
 - Client OS: windows 10
- Server OS: ubuntu 20.04
 - Browse type and version:  Version 83.0.4103.116 (Official Build) (64-bit)
- Cortex version:
 - Cortex Analyzer/Responder name: 3.0.1-1
- Cortex Analyzer/Responder version: 2.8.0

**Possible solutions**
deprecating the analyzer

**Additional context**

**Comment by dadokkio** [comment]
The free api are back online. Just tested the analyzer and works fine.
