### ISSUE TITLE
[FR] Merge new VMRay Analyzer

### ISSUE THREAD

**Issue by 53A-1** [TheHive-Project/Cortex-Analyzers#824]
I would like to kindly ask you to merge my pull request https://github.com/TheHive-Project/Cortex-Analyzers/pull/823 into the develop branch. It contains new functionality, deals with existing issues and cleans up the previous implementation in a few places.
Thanks to TKCERT's @mback2k for his work on this PR and thanks to you as a team for maintaining this great project.

**Comment by mback2k** [comment]
We just updated #823 with an improved commit history and I finished my tests of the analyzer successfully, it LGTM. :heavy_check_mark:
