### ISSUE TITLE
MalwareBazaar_1_0 doesn't support types of observables, but writed that it does[Bug]

### ISSUE THREAD

**Issue by NailBash** [TheHive-Project/Cortex-Analyzers#830]
I can launch MalwareBazaar_1_0 analyzer for this types of observables: domain, ip, fqdn, url, hash
![изображение](https://user-images.githubusercontent.com/29750691/88881912-1b8f2400-d24a-11ea-95df-eec00ec0707d.png)
But when I try do analyze for these types analyzer writes that not supported this types:
URL:
![изображение](https://user-images.githubusercontent.com/29750691/88882027-788ada00-d24a-11ea-9ff1-6c703895ce21.png)
IP
![изображение](https://user-images.githubusercontent.com/29750691/88882081-948e7b80-d24a-11ea-92e9-3de708342b8a.png)
Domain
![изображение](https://user-images.githubusercontent.com/29750691/88882109-a839e200-d24a-11ea-931a-2a0fa4602896.png)
It works only for hash
![изображение](https://user-images.githubusercontent.com/29750691/88882245-ed5e1400-d24a-11ea-8570-ab19c70453ae.png)

Sadly MalwareBazaar DB very poor

**Comment by garanews** [comment]
fixed in 2.9.0
