### ISSUE TITLE
PhishingInitiative_Scan_1_0 doesn't work[Bug]

### ISSUE THREAD

**Issue by NailBash** [TheHive-Project/Cortex-Analyzers#832]
**Describe the bug**
PhishingInitiative_Scan_1_0 doesn't work. I get API key and configured analyzer. Analyzer writes error
![изображение](https://user-images.githubusercontent.com/29750691/88888783-62841600-d258-11ea-991d-ec7adeb93bbb.png)

Something wrong with pyeupi I think.
Looks like PhishingInitiative_Lookup_2_0 works well
![изображение](https://user-images.githubusercontent.com/29750691/88889163-200f0900-d259-11ea-967d-539c9018cf58.png)

**Comment by dadokkio** [comment]
Are you running analyzer with python2 or python3? It seems from the error that is running with old python release not supported from PhishingInitiative api

**Comment by NailBash** [comment]
That was running by default python2, not I change this line to python3
![изображение](https://user-images.githubusercontent.com/29750691/88891506-c7416f80-d25c-11ea-8a53-d855e95ea2e9.png)

Now I have another error, it says that Service unavailable 
![изображение](https://user-images.githubusercontent.com/29750691/88891584-e2ac7a80-d25c-11ea-97ed-20b5c291bdb8.png)

**Comment by dadokkio** [comment]
Ok, I tried to run the code manually and there is something strange.
The scan api returns ```{    "status": {      "status": 401,      "message": "Unauthorized"    }}``` even if the key is valid for the lookup. 

The generic exception is not so clear in any case. I'll try to investigate better and then fix also the python3 missing.

**Comment by NailBash** [comment]
Ok, thank you for you answers and help

**Comment by garanews** [comment]
fixed in 2.9.0
