### ISSUE TITLE
PhishTank_CheckURL_2_1 doesn't work[Bug]

### ISSUE THREAD

**Issue by NailBash** [TheHive-Project/Cortex-Analyzers#833]
**Describe the bug**
I get API key for PhishTank_CheckURL_2_1, configured analyzer, but it don't work - writes error.
![изображение](https://user-images.githubusercontent.com/29750691/88890247-cb6c8d80-d25a-11ea-977e-96545adbec0b.png)

**Comment by dadokkio** [comment]
I just tried the analyzer with your url and it works as expected. 
From your error it seems that an invalid json has been returned from the api and that's strange cause normally if there is an error is reported directly in the returned json.

**Comment by NailBash** [comment]
Well, it looks like troubles with network
I writed this request in python, that should do same as analyzer 
![изображение](https://user-images.githubusercontent.com/29750691/89291017-34953c00-d673-11ea-8a54-fcfa2624839c.png)
and launched it at thehive and cortex server (error)
![изображение](https://user-images.githubusercontent.com/29750691/89291081-5262a100-d673-11ea-97a9-3611e37b6c4c.png)
but when I launch same script from my PC it worked well I think

![изображение](https://user-images.githubusercontent.com/29750691/89291499-14b24800-d674-11ea-8c8b-6bdad771875d.png)

**Comment by jeromeleonard** [comment]
Just made a test, and it also work well on my side. We are closing the issue unless you come with new information; in this case, please reopen.
