### ISSUE TITLE
New Analyzer: ElasticSearch Query

### ISSUE THREAD

**Issue by nicpenning** [TheHive-Project/Cortex-Analyzers#841]
**Feature description**
Query any ElasticSearch cluster or multiple clusters for any field and any index and return common fields that use the ElasticSearch Common Schema (ECS)

**Describe the solution you'd like**
This analyzer allows you to quickly query for URLs, IP addresses, domains, file hashes, and whatever other observables you choose. It will be great for threat intelligence reports or searching for those IOCs from an in house analysis on a phishing campaign.

**Features**
- [x] Query secured and insecure clusters
- [x] Ability to add any index pattern to search
- [x] Ability to add any field to search
- [x] Ability to limit the amount of results to return
- [x] Ability to extract observables
- [x] Ability to add tags for amount of results that get returned

We are nearly complete with this analyzer. Just applying some finishing touches and then we can supply the Pull Request.

**Comment by nicpenning** [comment]
Thanks @nmprokop for this contribution!

**Comment by nicpenning** [comment]
A preview of the analyzer:
![image](https://user-images.githubusercontent.com/5582679/95605781-0d663c80-0a1f-11eb-83a3-e03e099a232a.png)

**Comment by nicpenning** [comment]
Thanks @nmprokop for this contribution!

**Comment by nadouani** [comment]
I've already seen this one during a demo, and it's definitely a very good job.

@nicpenning @nmprokop we will review it and see in which release we can ship it. I think that 2.9.0 scope is already closed.

**Comment by nicpenning** [comment]
Woohoo! 
# 🔎🌲🪓🐝👌🚀🎉
