### ISSUE TITLE
Bluecoat Analyzer

### ISSUE THREAD

**Issue by 0xswitch** [TheHive-Project/Cortex-Analyzers#85]
### Request Type
 Feature

### Description
Adding a new analyzer for Cortex : **Bluecoat categorization**
PC #84

**Comment by 3c7** [comment]
Old issue. PR was merged, but with an recent update it isn't possible to query the website anymore. Also, using the bluecoat categorization in an automated way violates the terms of use, so there won't be an update from our side.
