### ISSUE TITLE
[Bug] OTXQuery_2_0 analyzer does not work

### ISSUE THREAD

**Issue by lukaszrzasik** [TheHive-Project/Cortex-Analyzers#850]
**Describe the bug**
OTXQuery_2_0 analyzer does not work after switching to python3.

**To Reproduce**
1. Configure OTXQuery_2_0 analyzer
2. Click New Analysis
3. Choose data type: ip
4. Put '8.8.8.8' into Data field
5. Mark OTXQuery_2_0 analyzer in the list of Analyzers.
6. Click Start

**Expected behavior**
A successful result from the analyzer.

**Actual behaviour**
The analyzer fails with the following error:
{
  "errorMessage": "API Error! Please verify data type is correct.",
  "input": "{\"dataType\":\"ip\",\"tlp\":2,\"data\":\"8.8.8.8\",\"pap\":2,\"config\":{\"max_pap\":2,\"jobTimeout\":30,\"auto_extract_artifacts\":false,\"key\":\"REMOVED\",\"check_pap\":true,\"proxy_http\":null,\"cacerts\":null,\"proxy_https\":null,\"max_tlp\":2,\"check_tlp\":true,\"jobCache\":10},\"message\":\"\",\"parameters\":{}}",
  "success": false
}

**Comment by lukaszrzasik** [comment]
The issue is solved by this PR: https://github.com/TheHive-Project/Cortex-Analyzers/pull/851

**Comment by dadokkio** [comment]
Merged in develop. Thanks for the fix!
