### ISSUE TITLE
[OSCD Initiative] Develop Responder for Palo Alto NGFW

### ISSUE THREAD

**Issue by yugoslavskiy** [TheHive-Project/Cortex-Analyzers#855]
**Feature description**

Responder for Palo Alto NGFW that would be able to execute the following Response Actions:

- [RA3101](https://atc-project.github.io/atc-react/Response_Actions/RA_3101_block_external_ip_address/): Block external IP address
- [RA3102](https://atc-project.github.io/atc-react/Response_Actions/RA_3102_block_internal_ip_address/): Block internal IP address
- [RA3103](https://atc-project.github.io/atc-react/Response_Actions/RA_3103_block_external_domain/): Block external domain
- [RA3104](https://atc-project.github.io/atc-react/Response_Actions/RA_3104_block_internal_domain/): Block internal domain
- [RA3105](https://atc-project.github.io/atc-react/Response_Actions/RA_3105_block_external_url/): Block external URL
- [RA3106](https://atc-project.github.io/atc-react/Response_Actions/RA_3106_block_internal_url/): Block internal URL
- [RA3107](https://atc-project.github.io/atc-react/Response_Actions/RA_3107_block_port_external_communication/): Block port external communication
- [RA3108](https://atc-project.github.io/atc-react/Response_Actions/RA_3108_block_port_internal_communication/): Block port internal communication
- [RA3109](https://atc-project.github.io/atc-react/Response_Actions/RA_3109_block_user_external_communication/): Block user external communication
- [RA3110](https://atc-project.github.io/atc-react/Response_Actions/RA_3110_block_user_internal_communication/): Block user internal communication
- [RA5101](https://atc-project.github.io/atc-react/Response_Actions/RA_5101_unblock_blocked_ip/): Unblock blocked IP
- [RA5102](https://atc-project.github.io/atc-react/Response_Actions/RA_5102_unblock_blocked_domain/): Unblock blocked domain
- [RA5103](https://atc-project.github.io/atc-react/Response_Actions/RA_5103_unblock_blocked_url/): Unblock blocked URL
- [RA5104](https://atc-project.github.io/atc-react/Response_Actions/RA_5104_unblock_blocked_port/): Unblock blocked port
- [RA5105](https://atc-project.github.io/atc-react/Response_Actions/RA_5105_unblock_blocked_user/): Unblock blocked user

**Describe the solution you'd like**

Access to Palo Alto NGFW via its API using one of the following projects:

- [pan-python](https://github.com/kevinsteves/pan-python)
- [pandevice](https://github.com/PaloAltoNetworks/pandevice)

or any other alternatives.

**Additional context**

Most probably the listed Response Actions will require pre-configured Security Policies (rules) that would be 1:1 mapped to the Response Actions. This way Cortext will just update these rules during the execution.

**Comment by yugoslavskiy** [comment]
Hello @jeromeleonard ! Are you going to work on the issue? I am also interested in this one, how about a collab? (:

**Comment by Konakin** [comment]
Hello. 
today, i got access to Palo Alto NGFW and i want create TheHive Responders. And i agree to collab :)
I can write to telegram.

**Comment by Konakin** [comment]
https://github.com/staf711/oscd_thehive_PaloAltoNGFW

**Comment by Konakin** [comment]
hello.
i want complete all responser today.

**Comment by Konakin** [comment]
i have problems with:
1. Block user
2. Unblock user
https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-new-features/user-id-features/dynamic-user-groups
in my test Palo Alto NGFW don't have any user and i can't step 5 in instruction (Register Users).

and i have problem with "Unblock blocked URL". I don't khown how delete url in list, but add i can.

If you know how to solve tihs problems, please tell me.

**Comment by Konakin** [comment]
Hello.
Plese see pull[#886](https://github.com/TheHive-Project/Cortex-Analyzers/pull/886).

next step: change logic and add rules for:
1. IP address
2. domains
3. URL(s)
4. ports
5. users

**Comment by yugoslavskiy** [comment]
Hello @Konakin! I've commented on your PR (: Let's proceed with the discussion there.

**Comment by jeromeleonard** [comment]
Thank you for your PR. We merged the related PR. Please consider translating the readme file from RU to EN.

Thanks.

**Comment by staf711** [comment]
@jeromeleonard, hi.
Sory i am late, but i translated README for PaloAlto responder #1025
