### ISSUE TITLE
[Bug] FileInfo/fileinfo_analyzer.py Missing Library

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/Cortex-Analyzers#866]
# FileInfo/fileinfo_analyzer.py Missing Library

### Request Type
Bug

### Problem Description
FileInfo is missing the `pyexifinfo` library.

```
Traceback (most recent call last):
  File "/opt/Cortex-Analyzers/analyzers/FileInfo/fileinfo_analyzer.py", line 2, in <module>
    import pyexifinfoImportError: No module named 'pyexifinfo'
```

**Comment by dadokkio** [comment]
Hi @milesflo , FileInfo analyzer have pyexifinfo in requirements and testing the docker image it works properly.
Are you testing the analyzer locally or on docker? In the first case have you manually installed requirements?

**Comment by milesflo** [comment]
This alert occurred from process-type execution, not on Docker. The error could lie in the dependency installation step

**Comment by jeromeleonard** [comment]
To install this library successfully, you need  `libimage-exiftool-perl` system package be installed.

**Comment by jeromeleonard** [comment]
hello, 

any feedback ? Can we close this issue ?
