### ISSUE TITLE
[Bug] TalosReputation_1_0. Failed to query Talos details. Status_code 503

### ISSUE THREAD

**Issue by NailBash** [TheHive-Project/Cortex-Analyzers#874]
Hello everyone. I have troubles with TalosReputation_1_0 analyzer. When I try launch it through Cortex web-ui or TheHive ui it returns error:
![изображение](https://user-images.githubusercontent.com/29750691/95091452-e9b1a680-073f-11eb-95df-dcb83ac3431a.png)
But when I copied analyzer code to simple python script and launched it worked as it should.
![изображение](https://user-images.githubusercontent.com/29750691/95091583-0fd74680-0740-11eb-84a5-90c0008a735f.png)
![изображение](https://user-images.githubusercontent.com/29750691/95091698-339a8c80-0740-11eb-82e5-8a349819a6be.png)

So it can't be troubles with my network or something. Pls, help!

**Comment by dadokkio** [comment]
Hi @NailBash , has been recently merged a pull that fixes this specific issue https://github.com/TheHive-Project/Cortex-Analyzers/pull/861 
At them moment has been merged just in develop, but you can test it if required

**Comment by romarito90** [comment]
Hello @NailBash Do you could fix the problem with talosreputation problem???

I'm having this problem when I run the analyzer 

![imagen](https://user-images.githubusercontent.com/114606380/207407098-70cda10b-579a-4440-bee1-84c105cd871b.png)

**Comment by finchy** [comment]
TalosIntelligence.com blocks scraping of the data in this way.

**Comment by romarito90** [comment]
> TalosIntelligence.com blocks scraping of the data in this way.

Hello @finchy thanks for your answer. Is there another way to get the ip reputation from talosintelligence, or only for subscription in talosintelligence???

**Comment by finchy** [comment]
You can look up things manually.  You cannot automate scraping of the site.  Please see my comment on #861

**Comment by romarito90** [comment]
> You can look up things manually. You cannot automate scraping of the site. Please see my comment on #861

OK, thanks for your answer.
