### ISSUE TITLE
Cortex Analysers problem

### ISSUE THREAD

**Issue by imad-testing** [TheHive-Project/Cortex-Analyzers#878]
Hello, I'm new to cortex. I am encountering this problem whenever use my analysers. Please can anyone help me?
![Capture1](https://user-images.githubusercontent.com/71173607/95842487-423fff80-0d4f-11eb-8582-44001674d70f.PNG)
![Capture2](https://user-images.githubusercontent.com/71173607/95842506-4704b380-0d4f-11eb-86c6-f19216124b42.PNG)

**Comment by garanews** [comment]
Hello, welcome on board!
Please describe your environment and your config file

**Comment by imad-testing** [comment]
**I am running my docker-compose file on ubuntu 18.04:**

**docker-compose.yml:**

version: "2"
services:


  kibana:
    image: kibana:5.6.0
    container_name: kibana
    ports:
     - "5601:5601"


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      -  script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - 1esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  thehive:
    image: thehiveproject/thehive:latest
    container_name: thehive
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - './thehive/:/etc/thehive/'
    command: --no-config-secret
    command: --cortex-port 9001 --cortex-key  tQqgFug13614Zf+6yvfoqC1K92SG1B8E --no-config


  cortex:
    container_name: cortex
    image: thehiveproject/cortex:latest
    ports:
      - "0.0.0.0:9001:9001"
    volumes:
      - './cortex/:/etc/cortex/'
      - './cortex/Cortex-Analyzers/analyzers:/opt/Cortex-Analyzers/analyzers:ro'
      - './cortex/Cortex-Analyzers/responders:/opt/Cortex-Analyzers/responders:ro'
    command: --no-config
    command: --no-config-secret
    depends_on:
      - elasticsearch



volumes:
  1esdata:



**The geo.py for maxmind is:**

#!/usr/bin/env python3
# encoding: utf-8
import os
import geoip2.database
from geoip2.errors import AddressNotFoundError
from cortexutils.analyzer import Analyzer


class MaxMindAnalyzer(Analyzer):

    def dump_city(self, city):
        return {
            'confidence': city.confidence,
            'geoname_id': city.geoname_id,
            'name': city.name,
            'names': city.names
        }

    def dump_continent(self, continent):
        return {
            'code': continent.code,
            'geoname_id': continent.geoname_id,
            'name': continent.name,
            'names': continent.names,
        }

    def dump_country(self, country):
        return {
            'confidence': country.confidence,
            'geoname_id': country.geoname_id,
            'iso_code': country.iso_code,
            'name': country.name,
            'names': country.names
        }

    def dump_location(self, location):
        return {
            'accuracy_radius': location.accuracy_radius,
            'latitude': location.latitude,
            'longitude': location.longitude,
            'metro_code': location.metro_code,
            'time_zone': location.time_zone
        }

    def dump_traits(self, traits):
        return {
            'autonomous_system_number': traits.autonomous_system_number,
            'autonomous_system_organization': traits.autonomous_system_organization,
            'domain': traits.domain,
            'ip_address': traits.ip_address,
            'is_anonymous_proxy': traits.is_anonymous_proxy,
            'is_satellite_provider': traits.is_satellite_provider,
            'isp': traits.isp,
            'organization': traits.organization,
            'user_type': traits.user_type
        }

    def summary(self, raw):
        taxonomies = []
        level = "info"
        namespace = "MaxMind"
        predicate = "Location"

        if "continent" in raw:
            value = "{}/{}".format(raw["country"]["name"], raw["continent"]["name"])
            taxonomies.append(self.build_taxonomy(level, namespace, predicate, value))

        return {"taxonomies": taxonomies}

    def run(self):
        Analyzer.run(self)

        if self.data_type == 'ip':
            try:
                data = self.get_data()

                city = geoip2.database.Reader(os.path.dirname(__file__) + '/GeoLite2-City.mmdb').city(data)

                self.report({
                    'city': self.dump_city(city.city),
                    'continent': self.dump_continent(city.continent),
                    'country': self.dump_country(city.country),
                    'location': self.dump_location(city.location),
                    'registered_country': self.dump_country(city.registered_country),
                    'represented_country': self.dump_country(city.represented_country),
                    'subdivisions': self.dump_country(city.subdivisions.most_specific),
                    'traits': self.dump_traits(city.traits)
                })
            except ValueError as e:
                self.error('Invalid IP address')
            except AddressNotFoundError as e:
                self.error('Unknown IP address')
            except Exception as e:
                self.unexpectedError(type(e))
        else:
            self.notSupported()


if __name__ == '__main__':
    MaxMindAnalyzer().run()

**the json file for maxmind:**

{
  "name": "MaxMind_GeoIP",
  "version": "4.0",
  "author": "CERT-BDF",
  "url": "https://github.com/TheHive-Project/Cortex-Analyzers",
  "license": "AGPL-V3",
  "description": "Use MaxMind to geolocate an IP address.",
  "dataTypeList": ["ip"],
  "baseConfig": "MaxMind",
  "command": "MaxMind/geo.py"
}

**It does not seem the issue is from maxmind specifically, because the analyser also failed when i tried it on abuseIPDB**

**Comment by imad-testing** [comment]
**In addition to that the docker-compose.yml file and the cortex file are here:**

![image](https://user-images.githubusercontent.com/71173607/95856628-f7c87e00-0d62-11eb-9433-22dde7bc9707.png)

![image](https://user-images.githubusercontent.com/71173607/95856680-13cc1f80-0d63-11eb-9a42-2fa878d87224.png)


**My application.conf:**

 # Sample Cortex application.conf file

## SECRET KEY
#
# The secret key is used to secure cryptographic functions.
#
# IMPORTANT: If you deploy your application to several  instances,  make
# sure to use the same key.
play.http.secret.key="B4FvQWnTp718vr6AHyvdGlrHBGNcvuM4y3jUeRCgXxIwBZIbt"

## ElasticSearch
search {
  # Name of the index
  index = cortex
  # ElasticSearch instance address.
  # For cluster, join address:port with ',': "http://ip1:9200,ip2:9200,ip3:9200"
  uri = "http://elasticsearch:9200"

  ## Advanced configuration
  # Scroll keepalive.
  #keepalive = 1m
  # Scroll page size.
  #pagesize = 50
  # Number of shards
  #nbshards = 5
  # Number of replicas
  #nbreplicas = 1
  # Arbitrary settings
  #settings {
  #  # Maximum number of nested fields
  #  mapping.nested_fields.limit = 100
  #}

  ## Authentication configuration
  #search.username = ""
  #search.password = ""

  ## SSL configuration
  #search.keyStore {
  #  path = "/path/to/keystore"
  #  type = "JKS" # or PKCS12
  #  password = "keystore-password"
  #}
  #search.trustStore {
  #  path = "/path/to/trustStore"
  #  type = "JKS" # or PKCS12
  #  password = "trustStore-password"
  #}
}

## Cache
#
# If an analyzer is executed against the same observable, the previous report can be returned without re-executing the
# analyzer. The cache is used only if the second job occurs within cache.job (the default is 10 minutes).
cache.job = 10 minutes

## Authentication
auth {
	# "provider" parameter contains the authentication provider(s). It can be multi-valued, which is useful
	# for migration.
	# The available auth types are:
	# - services.LocalAuthSrv : passwords are stored in the user entity within ElasticSearch). No
	#   configuration are required.
	# - ad : use ActiveDirectory to authenticate users. The associated configuration shall be done in
	#   the "ad" section below.
	# - ldap : use LDAP to authenticate users. The associated configuration shall be done in the
	#   "ldap" section below.
	provider = [local]

	ad {
		# The Windows domain name in DNS format. This parameter is required if you do not use
		# 'serverNames' below.
		#domainFQDN = "mydomain.local"

		# Optionally you can specify the host names of the domain controllers instead of using 'domainFQDN
		# above. If this parameter is not set, TheHive uses 'domainFQDN'.
		#serverNames = [ad1.mydomain.local, ad2.mydomain.local]

		# The Windows domain name using short format. This parameter is required.
		#domainName = "MYDOMAIN"

		# If 'true', use SSL to connect to the domain controller.
		#useSSL = true
	}

	ldap {
		# The LDAP server name or address. The port can be specified using the 'host:port'
		# syntax. This parameter is required if you don't use 'serverNames' below.
		#serverName = "ldap.mydomain.local:389"

		# If you have multiple LDAP servers, use the multi-valued setting 'serverNames' instead.
		#serverNames = [ldap1.mydomain.local, ldap2.mydomain.local]

		# Account to use to bind to the LDAP server. This parameter is required.
		#bindDN = "cn=thehive,ou=services,dc=mydomain,dc=local"

		# Password of the binding account. This parameter is required.
		#bindPW = "***secret*password***"

		# Base DN to search users. This parameter is required.
		#baseDN = "ou=users,dc=mydomain,dc=local"

		# Filter to search user in the directory server. Please note that {0} is replaced
		# by the actual user name. This parameter is required.
		#filter = "(cn={0})"

		# If 'true', use SSL to connect to the LDAP directory server.
		#useSSL = true
	}
}

## ANALYZERS
#
analyzer {
  # analyzer location
  # url can be point to:
  # - directory where analyzers are installed
  # - json file containing the list of analyzer descriptions
  urls = [
    #"https://dl.bintray.com/thehive-project/cortexneurons/analyzers.json"
    "/opt/Cortex-Analyzers/analyzers"
  ]

  # Sane defaults. Do not change unless you know what you are doing.
  fork-join-executor {
    # Min number of threads available for analysis.
    parallelism-min = 2
    # Parallelism (threads) ... ceil(available processors * factor).
    parallelism-factor = 2.0
    # Max number of threads available for analysis.
    parallelism-max = 4
  }
}

# RESPONDERS
#
responder {
  # responder location (same format as analyzer.urls)
  urls = [
    #"https://dl.bintray.com/thehive-project/cortexneurons/reponders.json"
    "/opt/Cortex-Analyzers/responders"
  ]

  # Sane defaults. Do not change unless you know what you are doing.
  fork-join-executor {
    # Min number of threads available for analysis.
    parallelism-min = 2
    # Parallelism (threads) ... ceil(available processors * factor).
    parallelism-factor = 2.0
    # Max number of threads available for analysis.
    parallelism-max = 4
  }
}

# It's the end my friend. Happy hunting!

**But it do not seem like i'm using my application.conf file to run cortex. I'm sorry the environment is so new to me**

**Comment by garanews** [comment]
Thanks.
passing ` command: --no-config` means that you don't want cortex uses default application.conf file. 
This is fine, but you should map an external application.conf file  for example:

``` 
   volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf```

**Comment by garanews** [comment]
Good.
With external application.conf you have more control, in case you need to configure different elastic server instead localhost, authentication methofds, etc.
To map it, as i suggested, map directly the application.conf file:  ``` - ./cortex/application.conf:/etc/cortex/application.conf```


For your info, if you want to start to play with new versions of tools like thehive4 (that uses cassandra as db) and cortex 3.1 (that uses elastic 7.x instead 6,x) you can have a look here: https://github.com/TheHive-Project/TheHive/tree/develop-th4/docker
In this docker compose there is also MISP and an automation tool, that you can remove if not needed.

**Comment by imad-testing** [comment]
Oh great! Thank you so much! Will keep you posted about any news or problems that I will face in the future.

**Comment by dadokkio** [comment]
I'm going to close the issue, if you have any other issue reopen it.
