### ISSUE TITLE
LDAP3 Module not found on cortex analyser

### ISSUE THREAD

**Issue by imad-testing** [TheHive-Project/Cortex-Analyzers#883]
Hello, I'm trying to develop an analyser that get the SID from a user in a specific active directory and return user infos. I installed ldap3 module but it always give me an error. Please can someone help?

![image](https://user-images.githubusercontent.com/71173607/96233487-ef5d8680-0fa0-11eb-81a5-5506f4bcab72.png)

![image](https://user-images.githubusercontent.com/71173607/96233756-2d5aaa80-0fa1-11eb-8d7d-5fa2e9a59383.png)

![image](https://user-images.githubusercontent.com/71173607/96233871-54b17780-0fa1-11eb-9dd4-e3f85bbed341.png)

**Comment by dadokkio** [comment]
can you check if ldap3 is properly installed?
A simple `pip3 list | grep ldap` should return something similar:
```
>>> pip3 list | grep ldap
ldap3                  2.8
```

 A classic error is to install it with pip (python2) instead of pip3 (python3) or picking the wrong ldap lib.

**Comment by imad-testing** [comment]
I checked it. Any recommendations?
![image](https://user-images.githubusercontent.com/71173607/96249460-e1663080-0fb5-11eb-87f0-cb22f7863c25.png)

**Comment by garanews** [comment]
If you are running cortex in docker, you should install libs inside cortex docker image

**Comment by imad-testing** [comment]
I'm always facing the same error. I entered the docker container and I installed ldap3. Any recommendations?

![image](https://user-images.githubusercontent.com/71173607/96257389-f1d0d800-0fc2-11eb-947e-32d03a476ef9.png)

**Comment by imad-testing** [comment]
Alright, I installed it inside docker with "pip install ldap3" but then it showed me alot of errors. I tried the python code on spyder, it runs without errors. What is the problem here?

 
![image](https://user-images.githubusercontent.com/71173607/96261390-116aff00-0fc9-11eb-8038-d590f64c2c21.png)

**Comment by dadokkio** [comment]
I think is related to selected attributes, can you try using only `attributes=['sAMAccountName']` paying attention to capital letters ?

**Comment by imad-testing** [comment]
![image](https://user-images.githubusercontent.com/71173607/96279105-ee4b4a00-0fde-11eb-9062-6e3fe17a65ba.png)

I tried this but still errors ...

**Comment by dadokkio** [comment]
Ok.. then I'll suggest to use attributes = ldap3.ALL_ATTRIBUTES to extract all the attributes and fix that later when you see what is present in your ldap server..

**Comment by imad-testing** [comment]
I'm sorry for all my questions. Thank you anw for your help. It showed also some errors.

![image](https://user-images.githubusercontent.com/71173607/96302554-b43f6f80-1001-11eb-86a8-6136b223cdca.png)

![image](https://user-images.githubusercontent.com/71173607/96302590-c0c3c800-1001-11eb-8408-74aff42aed7d.png)

**Comment by dadokkio** [comment]
ok you can add:
`import ldap`

or add ALL_ATTRIBUTES in
`from ldap import Server, Connection, ALL, ALL_ATTRIBUTES`
and change ldap.ALL_ATTRIBUTES to just ALL_ATTRIBUTES

**Comment by imad-testing** [comment]
It showed me the same error then before.
![image](https://user-images.githubusercontent.com/71173607/96331172-d23dbc00-1063-11eb-96eb-7c42d073258f.png)
![image](https://user-images.githubusercontent.com/71173607/96331174-dbc72400-1063-11eb-8e32-16d79536d689.png)

**Comment by imad-testing** [comment]
I tried it with import ldap3. It showed me that the Server is not defined. But it should be because i imported all the module.
![image](https://user-images.githubusercontent.com/71173607/96331320-12ea0500-1065-11eb-8f42-cc007da77894.png)

**Comment by dadokkio** [comment]
In this case you had to add the import to the existing one

**Comment by imad-testing** [comment]
> In this case you had to add the import to the existing one

Sorry but I didn't get your point

**Comment by dadokkio** [comment]
Keep them both

`import ldap

from ldap import Server, Connection, ALL`

**Comment by imad-testing** [comment]
I did that but also the same problem

**Comment by dadokkio** [comment]
I wrote [a test analyzer based from your code](https://gist.github.com/dadokkio/7223e2fe082d7f83781457a47cb676ee) and it's working fine.
The strategy to download all the users/group and then check the sid isn't efficient if the number of them is huge (like in my case)

**Comment by imad-testing** [comment]
Thank you! It is working also with me

**Comment by imad-testing** [comment]
**I have also a question, I am writing another script that let me enable disable users. when I test it from analysers it works but when i test it from responders it does not appear in analysers when I choose the datatype = sid. What could be the problem?**

**json file:**
{
    "name": "Active Directory Enable Disable",
    "version": "1.0",
    "author": "Imad Boustany",
    "url": "https://github.com/TheHive-Project/Cortex-Analyzers",
    "license": "AGPL-v3",
    "description": "Enable/Disable Users in active directory",
    "baseConfig": "Active_Directory_Enable_Disable",
    "dataTypeList": ["sid"],
    "command": "Active_Directory_Enable_Disable/Active_Directory_Enable_Disable.py",
    "configurationItems": [
      {
        "name": "domain",
        "description": "root domain dc=hello,dc=com",
        "type": "string",
        "multi": false,
        "required": true
      },
      {
        "name": "Administrator",
        "description": "Please enter a user with administrative priviledges CN=Administrator,DC=hello,DC=com",
        "type": "string",
        "multi": false,
        "required": true,
        "defaultValue": "CN=Administrator    "
      },
      {
        "name": "User",
        "description": "Please enter the User to Enable/Disable CN=User,DC=hello,DC=com",
        "type": "string",
        "multi": false,
        "required": true
      },
      {
        "name": "Enable_Disable",
        "description": "Type E to Enable and D to Disable",
        "type": "string",
        "multi": false,
        "required": true
      },
      {
        "name": "password",
        "description": "password",
        "type": "string",
        "multi": false,
        "required": true
      },
      {
        "name": "ip",
        "description": "ip address of the domain controller",
        "type": "string",
        "multi": false,
        "required": true
      }
    ]
}





![image](https://user-images.githubusercontent.com/71173607/97085434-33e2c500-1626-11eb-8c54-8c86a0ae2efe.png)

**Comment by dadokkio** [comment]
Responders are located on different position than analyzer.
You can find them in the observable detail: the :gear: under the Actions folder on the right.
![image](https://user-images.githubusercontent.com/355183/97675327-6b6ec880-1a8f-11eb-9780-568399934e46.png)

Or in case/observable list: on the top action the :gear: Responders link
![image](https://user-images.githubusercontent.com/355183/97675390-86413d00-1a8f-11eb-8e8a-d1b299fb3c8c.png)

**Comment by imad-testing** [comment]
Thanks you for your help
