### ISSUE TITLE
System proxy settings not set using global configuration 

### ISSUE THREAD

**Issue by magnumchoucroute** [TheHive-Project/Cortex-Analyzers#884]
**Describe the bug**
Proxy setting define in Global Configuration is not  is not take into account

![plop](https://user-images.githubusercontent.com/72990953/96286103-243cfe00-0fe0-11eb-8bbb-c0ec4f0f6848.png)

**Work environment**
 - Client OS:  Win10
- Server OS: CentOs 7 
 - Browse type and version: Chrome anD Firefox 
- Cortex version: cortex-3.1.0-RC1-1
- Cortex Analyzer/Responder name: TorProject
- Cortex Analyzer/Responder version:   1.0

**To Reproduce**
1. Set Proxy into Global Configuration
1. Run a cortex analyzer which use online query
 

**Error log from Cortex  using TorProject analyzer**
[info] o.t.c.s.ProcessJobRunnerSrv -   Job Z2s7MnUBTHsOEp4HtthD: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='check.torproject.org', port=443): Max retries exceeded with url: /exit-addresses (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efee5bb40f0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[info] o.t.c.s.AuditActor - Job Z2s7MnUBTHsOEp4HtthD has be updated (JsDefined("Failure"))
[info] o.t.c.s.JobSrv - Job Z2s7MnUBTHsOEp4HtthD has finished with status Failure

**Possible solutions**
?

**Additional context**

**Comment by dadokkio** [comment]
Hi @magnumchoucroute can you please check if proposed pull helps with the issue?

**Comment by jeromeleonard** [comment]
Hello @magnumchoucroute 

- Are you running the analyzer with docker or with the process on the Cortex host ?
- Can you confirm that with Cortex 3.1.0 that has been released recently ?
- Did you setup the proxy in the Global configuration after have enabled the analyzer ? if yes you need either to configure the analyzer or disable en re-enable it to take proxy configuration into account. 

Thank you.

**Comment by jeromeleonard** [comment]
no feedback, closed.
