### ISSUE TITLE
[Bug] Splunk TypeError jobResult["resultCount"] implicit int cast

### ISSUE THREAD

**Issue by manwefm** [TheHive-Project/Cortex-Analyzers#896]
Hi, here is a simple bug, i don't know if opening an issue was necessary, maybe a pull request may have done it but here it is :

**Describe the bug**
File "/path/Cortex-Analyzers/analyzers/Splunk/splunk.py", line 141, in SplunkSearch    jobResult["note"] = "Only the first "+str(self.MAX_COUNT)+" results were recovered over "+jobResult["resultCount"]+" to avoid any trouble on TheHive/Cortex. This parameter (max_count) can be changed in the analyzer configuration."TypeError: Can't convert 'int' object to str implicitly

**To Reproduce**
1. Using any of Splunk_Search_*, use a splunk search that returns more results than MAX.COUNT

**Expected behavior**
No TypeError

**Work environment**
 - Client OS: Chrome
- Server OS: Ubuntu 20.04
 - Browse type and version:
- Cortex version: 3.0.1-1
 - Cortex Analyzer/Responder name: Splunk
- Cortex Analyzer/Responder version: 3.0

**Possible solutions**
On Cortex-Analyzers/analyzers/Splunk/splunk.py:141 :
str(jobResult["resultCount"])
instead of
jobResult["resultCount"]

I will make a pull request asap linked to this issue. I hope I'm doing everything right...

**Comment by dadokkio** [comment]
maybe an format is a better option?

`jobResult["note"] = "Only the first {} results were recovered over {} to avoid any trouble on TheHive/Cortex. This parameter (max_count) can be changed in the analyzer configuration.".format(self.MAX_COUNT, jobResult["resultCount"])`

**Comment by manwefm** [comment]
Sure, i agree, i will do that.
