### ISSUE TITLE
[Bug] CortexNeurons error parsing version in analyzer.json or responder.json

### ISSUE THREAD

**Issue by azgaviperr** [TheHive-Project/Cortex-Analyzers#901]
**Describe the bug**
While the version of  analyzer is described in the manifest contain a "x.0", Cortex try to pull only the tag x instead of x.0.
Maybe this is due to a script converting it as number instead of string.

**To Reproduce**
1. Try to execute the responder redmine as it is delcared as 2.0 and don't have a tag: 2 on dockerhub
2. See cortex failing to find a suitable image for this responder.

**Expected behavior**

It should be possible de download the proper image version declared in the manifest if it containe x.0

**Comment by dadokkio** [comment]
Hello, are you sure the responder is redmine 2.0? The version in the json is 1.0 and that could explain why the docker image for 2.0 is not available

**Comment by azgaviperr** [comment]
Sorry, I mispell it, yes it's 1.0

**Comment by azgaviperr** [comment]
The issue seems to be interpreting 1.0 as a value and use it as an "int" so "1.0" become "1" instead of a float as Emlparser which is 1.2 is properlly pulled.

**Comment by dadokkio** [comment]
I'm running few docker images tagged as 1.0 without issues.. can you please add the related error from cortex?

**Comment by azgaviperr** [comment]
docker pull cortexneurons/redmine_issue:1  Error image not found

Sorry got an issue with the rate limit right now, but the message was pretty much that

**Comment by dadokkio** [comment]
Ok, I was able to replicate the issue. I was using the -devel.json list and there the image was fine.
@jeromeleonard probably drone for master must be rerun in order to finalize "recently added" analyzer/responder images. Can you please check?

**Comment by jeromeleonard** [comment]
we are looking at it
