### ISSUE TITLE
[FR] New Analyzer: Palo Alto Wildfire Sandbox

### ISSUE THREAD

**Issue by nachorpaez** [TheHive-Project/Cortex-Analyzers#910]
**Feature description**
Query Wildfire Public API to get detailed information about an URL or file.
Analyzer will require valid Wildfire subscription.

Will support the following data types:
- File
- Hash
- URL

**Describe the solution you'd like**
This analyzer will allow you to submit URL's and files to Wildfire sandbox. Also it will allow analysts to query for verdict and detailed report of URL and hashes.

**Additional context**
Will use the Palo Alto API for Wildfire https://docs.paloaltonetworks.com/wildfire/u-v/wildfire-api

**Comment by nachorpaez** [comment]
Managed to create the analyzer but got a bit lost on getting the best way to show all the information on the reporting template.

Won't be able to keep working on this because I no longer have access to a Wildfire subscription.

Pushed all my code in [my fork](https://github.com/nachorpaez/Cortex-Analyzers/commit/e7598a15667309df4e39313d3454d2174096908d) in case someone wants to keep working on it.

**Comment by joeslazaro-cdw** [comment]
I've got the analyzer and report working perfectly and I'll be submitting a PR soon.
