### ISSUE TITLE
Censys analyzer is failing

### ISSUE THREAD

**Issue by dadokkio** [TheHive-Project/Cortex-Analyzers#917]
Thanks !

Not sure if its related, but upon futher testing the Censys_1_0 analyzer failed to work as well :

`Traceback (most recent call last): File "/opt/Cortex-Analyzers/analyzers/Censys/censys_analyzer.py", line 6, in <module> from censys.base import CensysNotFoundException, CensysRateLimitExceededException, CensysUnauthorizedExceptionImportError: cannot import name 'CensysNotFoundException' from 'censys.base' (/usr/local/lib/python3.8/dist-packages/censys/base.py)`

_Originally posted by @aim4r in https://github.com/TheHive-Project/Cortex-Analyzers/issues/914#issuecomment-745579989_

**Comment by smclinden** [comment]
If you are using the public API rather than the ASM, you need to change the censys related headers in censys_analyzer.py to:

```
from censys.search import SearchClient, CensysCertificates, CensysData, CensysIPv4, CensysWebsites, CensysHosts
from censys.common.exceptions import CensysNotFoundException, CensysRateLimitExceededException, CensysUnauthorizedException
```

**Comment by D4rkw0lv3s** [comment]
> 
> 
> If you are using the public API rather than the ASM, you need to change the censys related headers in censys_analyzer.py to:
> 
> ```
> from censys.search import SearchClient, CensysCertificates, CensysData, CensysIPv4, CensysWebsites, CensysHosts
> from censys.common.exceptions import CensysNotFoundException, CensysRateLimitExceededException, CensysUnauthorizedException
> ```

@smclinden  It did not work as well. It gives the following error: 
```
Traceback (most recent call last):  File "/opt/Cortex-Analyzers/analyzers/Censys/censys_analyzer.py", line 9, in <module>    from censys.search import SearchClient, CensysCertificates, CensysData, CensysIPv4, CensysWebsites, CensysHostsModuleNotFoundError: No module named 'censys.search'
```

![image](https://user-images.githubusercontent.com/21691729/120460139-bee02680-c390-11eb-86a2-3b020b683382.png)

**Comment by smclinden** [comment]
I used the most recent (at the time of the original posting) version of censys-python from GitHub.  https://github.com/censys/censys-python/

**Comment by nadouani** [comment]
Hello folks, any news on this ? We will postpone it for 3.1.0 until a fix is available.

**Comment by dadokkio** [comment]
I think this has been fixed here.. https://github.com/TheHive-Project/Cortex-Analyzers/commit/c0cb7f8a214ecea70bd5ce91f2014c4ec861278e#diff-72cabf7350aa394a58a826df82d5f868402a54f2377d5afc0eb8d8f0188e606e
