### ISSUE TITLE
[Bug] Changes to Application.conf 

### ISSUE THREAD

**Issue by victorhugo-sg** [TheHive-Project/Cortex-Analyzers#918]
**Describe the bug**
I noticed that the usual commented path = has been removed. Can someone assist me w/ this code? Am I coding this correctly. 

Im running Cortex 3.1.0-RC-1

**To Reproduce**
Modify application.conf

analyzer {

     urls = ["https://dl.bintray.com/thehive-project/cortexneurons/analyzers.json"]
  **path = ["/opt/Cortex-Analyzers/analyzers/"] - This is what I added. is this in the correct spot and form?** 

**Expected behavior**
I expect the analyzers to show up in the GUI.

**Work environment**

- Server OS: Ubuntu 20.04
 - Browse type and version:
- Cortex version: 3.1.0-RC1-1

**Possible solutions**
N/A

**Additional context**

**Comment by D4rkw0lv3s** [comment]
I'm using:  
`urls = ["/opt/Cortex-Analyzers/analyzers/"]`

and it's working fine.

**Comment by dadokkio** [comment]
Yes, it's correct. The only thing you need to check also is job that is different for local or docker runs:
```
job {
  runner = [local]
}
```

**Comment by victorhugo-sg** [comment]
I changed it to the examples provided above and it appears to be working. Thank you.
