### ISSUE TITLE
[FR] Responder which sends a mail with a detailed incident status 

### ISSUE THREAD

**Issue by mkcorpc** [TheHive-Project/Cortex-Analyzers#920]
**Feature description**
Mail a detailed status information of an incident case including incident id, name, severity, custom fields, etc. The mail is sent to recipients specified by tags prefixed with 'mail='. The responder respects tlp definitions. For tlp:amber mail address and for tlp:green mail domains must be pre-defined in the configuration. For tlp:red sending mails is denied. The responser also uses thehive4py to collect information about the status of the tasks of the incidents.

**Describe the solution you'd like**
A new responder should be developed. A second options would be to replace the Mailer responder. I am not sure, but i think the 'Mailer' just sends an empty mail.

**Additional context**
No additional context

**Comment by dadokkio** [comment]
Closing issue since pull has been merged
