### ISSUE TITLE
[Bug] Hashdd not working

### ISSUE THREAD

**Issue by hefesita** [TheHive-Project/Cortex-Analyzers#931]
**Describe the bug**
Hashdd is not working, either the endpoint is not found or the method is not allowed.

**To Reproduce**
I have configured Hashdd as a Cortex Analyzer and when I try to use it I have an error:
404 Client Error: NOT FOUND for url: https://api.hashdd.com/detail

I modify the analyzer to point to the endpoint in their API docs (https://www.hashdd.com/#api):
https://api.hashdd.com/v1/detail/hash I still get an error  405 Client Error: METHOD NOT ALLOWED.
Looking at the code, the method used is POST and I think it should be GET. 

**Work environment**
- Server OS: CentOS 8
- Cortex version: 3
 - Cortex Analyzer/Responder name: Hashdd_Detail_1_0
- Cortex Analyzer/Responder version: Version: 1.0

**Comment by dadokkio** [comment]
I was able to fix login and query..but the return details are now a list instead of a simple json.. tomorrow morning I'll find a good way to update templates and push fix

**Comment by dadokkio** [comment]
I made a pull in develop if you want to test. 
In the template there is now a list of results so I tried to put common info on top.
![image](https://user-images.githubusercontent.com/355183/106254379-ee332b00-6218-11eb-9a2d-b989f02661de.png)
If you have any suggestion let me know.

**Comment by hefesita** [comment]
Thanks! I will test it today and let you know
