### ISSUE TITLE
Analyzers don't work

### ISSUE THREAD

**Issue by AngelaSvoykina** [TheHive-Project/Cortex-Analyzers#939]
I used docker for install thehive.  But when i run analyzer a have mistake.
![image](https://user-images.githubusercontent.com/11028262/107618790-344dad00-6c63-11eb-80f4-28288f878bf2.png)
![image](https://user-images.githubusercontent.com/11028262/107618847-492a4080-6c63-11eb-8114-de2e1ad25ff2.png)
![image](https://user-images.githubusercontent.com/11028262/107618881-547d6c00-6c63-11eb-9a9f-3c5636e998da.png)
My configuration
![image](https://user-images.githubusercontent.com/11028262/107618921-6232f180-6c63-11eb-89c7-96ccdd8b2f87.png)
![image](https://user-images.githubusercontent.com/11028262/107618951-6ced8680-6c63-11eb-9019-019cc8436d1c.png)
![image](https://user-images.githubusercontent.com/11028262/107618976-77a81b80-6c63-11eb-9395-15c35e3d9566.png)

**Comment by AngelaSvoykina** [comment]
![image](https://user-images.githubusercontent.com/11028262/107619047-9c9c8e80-6c63-11eb-9cc6-320239a1b957.png)

**Comment by AngelaSvoykina** [comment]
![image](https://user-images.githubusercontent.com/11028262/107621878-fdc66100-6c67-11eb-977a-2a0649dbfc12.png)

**Comment by dadokkio** [comment]
I think that the last picture before the one with thehive logo has a problem.
It seems a merge of application.conf for thehive (the first part where you specify url and key) with application.conf for cortex (where you specify the analyzers url)
The application.conf from cortex is also in the second image, where url for analyzer are empty.

If you are just testing I suggest to give a look to https://github.com/TheHive-Project/Docker-Templates and start with the most detailed [like https://github.com/TheHive-Project/Docker-Templates/blob/main/docker/thehive4-cortex3-misp-shuffle/README.md that has a good explanation]

**Comment by AngelaSvoykina** [comment]
> I think that the last picture before the one with thehive logo has a problem.
> It seems a merge of application.conf for thehive (the first part where you specify url and key) with application.conf for cortex (where you specify the analyzers url)
> The application.conf from cortex is also in the second image, where url for analyzer are empty.
> 
> If you are just testing I suggest to give a look to https://github.com/TheHive-Project/Docker-Templates and start with the most detailed ones ([like this for th4](https://github.com/TheHive-Project/Docker-Templates/blob/main/docker/thehive4-cortex3-misp-shuffle/README.md) that has a good explanation)
Thank you! Second time? i used docker for ubuntu 20.04 and have same mistakes

**Comment by AngelaSvoykina** [comment]
![Uploading mistake.png…]()

**Comment by AngelaSvoykina** [comment]
![image](https://user-images.githubusercontent.com/11028262/108069695-b4657f80-7074-11eb-93bd-ac6ed65873a6.png)

**Comment by AngelaSvoykina** [comment]
![Uploading mistake.png…]()

**Comment by AngelaSvoykina** [comment]
![image](https://user-images.githubusercontent.com/11028262/108069805-d65f0200-7074-11eb-9ea2-7cf000191558.png)

**Comment by AngelaSvoykina** [comment]
![Uploading image.png…]()

**Comment by AngelaSvoykina** [comment]
![Uploading image.png…]()

**Comment by dadokkio** [comment]
Going to close this. Feel free to reopen if necessary.
