### ISSUE TITLE
[Bug]Cisco Umbrella Responder

### ISSUE THREAD

**Issue by vxsh4d0w** [TheHive-Project/Cortex-Analyzers#954]
**Describe the bug**
Cisco Umbrella responder generates this error when is launched: **Request error: POST unix://localhost:80/images/create?fromImage=cortexneurons%2Fumbrella+blacklister&tag=1: 400, body: {"message":"invalid reference format"}**

**To Reproduce**
1. Configure the responder on Cortex, setting the integration url
1. Open a case on TheHive and add an observable like a domain
1. Select the observable and then click on "Responders" and launch the Umbrella one.

**Expected behavior**
It is expected to send a POST request to Umbrella and blacklist the selected observable.

**Complementary information**
Here is a screenshot:
![bug](https://user-images.githubusercontent.com/45754825/109645393-10410580-7b57-11eb-9f38-7c4db60b654a.PNG)

**Work environment**
- Server OS: Ubuntu Server 20.04
 - Browse type and version: Firefox 86
- Cortex version: 3.1.0-1
 - Cortex Analyzer/Responder name: Umbrella Blacklister
- Cortex Analyzer/Responder version: 1.1

**Comment by vxsh4d0w** [comment]
domain and urls (same thing I do on Umbrella Console)

**Comment by arnydo** [comment]
It should work for `["domain", "url", "fqdn"]`. I am setting up a new instance now and Ill see if I can replicate your issue.

**Comment by arnydo** [comment]
I just successfully sent a domain and URL to the responder using a fresh install of TheHive/Cortex.
Did you verify you have correct file permissions applied to the responder files?

**Comment by vxsh4d0w** [comment]
I'm using docker...so i suppose yes. It should use the right permission.

**Comment by arnydo** [comment]
I have not run the responder in Docker yet so I am not sure what the differences may be. May want to double check to make sure.

**Comment by vxsh4d0w** [comment]
Thanks so much. Let me know if there is something I have to do to help you.

**Comment by VictorThoren** [comment]
@vxsh4d0w We just ran into the same issue (also running with Docker). Did you figure you it out?

**Comment by jeromeleonard** [comment]
Hello,

this error indicates that docker cannot pull the image. After a test, the image is available. Closing the issue.
