### ISSUE TITLE
TLP checks

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/Cortex-Analyzers#96]
### Request Type
Feature

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| Cortex Analyzer Name      | *
| Cortex Analyzer Version   | 1.6.3
| Cortex Version            | 1.1.3

### Description
I have a generic question about TLP checks and limits per analyzers If this is not the place for that question I apologize.

I understand the need for "active" analysis such as VirusTotal scans and such. But I am not sure why some rather passive analyzers are allowed to run analysis only on observables with a green TLP or less. 

What are your recommendations on TLP definitions?

Additionally, would you consider a feature request to allow overriding the TLP limit for an analyzer?

**Comment by nadouani** [comment]
Hello, I'll start by answering the last question: You are already able to override the TLP definition for any analyzer. You should be even able to disable the TLP check if you want: just edit the Cortex configuration file `/etc/cortex/applicattion.conf` and set the following properties to the analyzer you want to override:

- `check_tlp`: set it to false to disable the check (not recommended)
- `max_tlp`: 0, 1, 2, 3 for WHITE,GREEN,AMBER and RED respectively. this value represent the max TLP that the analyzer can process. If you have a TLP:RED IP, and max_tlp is set to 2 (AMBER) then the analyzer will throw an error

Note that, the analyzer configuration will be possible from the UI, starting from Cortex 2: the administrators will be able to use a Web UI to modify the analyzers' config

**Comment by srilumpa** [comment]
Sorry to reopen this but I wasn't able to override the `check_tlp` or `max_tlp` settings through the application.conf file.

I tried the following settings and each time restarted cortex and tried to analyze a tlp:AMBER artifact, but none of them worked.

Deactivating TLP checks:
```
GoogleSafebrowsing {
  key = "[redacted]"
  check_tlp = false
}
```

With a `max_tlp` as an integer:
```
GoogleSafebrowsing {
  key = "[redacted]"
  max_tlp = 2
}
```

With a `max_tlp` as a string:
```
GoogleSafebrowsing {
  key = "[redacted]"
  max_tlp = "2"
}
```

Am I wrong to assume that this configuration can only be done in the various analyzers JSON configuration files?

**Comment by nadouani** [comment]
Hello @srilumpa well, the JSON configuration files are not supposed to be updated. If customizing the analyzer's config doesn't work, we can investigate. I'll reopen the issue, and let you know.

**Comment by saadkadhi** [comment]
@jeromeleonard any update on this front? /cc @nadouani

**Comment by jeromeleonard** [comment]
Hi @srilumpa,

if you want to change `max_tlp` and `check_tlp` it is better to do it in json configuration files of each analyzers you want to customize. The configuration given as input to an analyzer is considered in this order : 
1. the gobal configuration found in cortex `application.conf` file (typically proxy settings)
2. the baseConfig of an analyzer found in cortex `application.conf` file 
3. the dedicated configuration of the analyzer detailed in the .json file.

So, indeed, if you specified `max_tlp` and `check_tlp` in both the baseConfig (application.conf) and the dedicated configuration (.json) of an analyzer, the one specified in the .json file will be taken into account and given as input to run the analyzer.

**Comment by srilumpa** [comment]
Ok, thank you for your clarifications @jeromeleonard.

**Comment by jeromeleonard** [comment]
yw.
