### ISSUE TITLE
[FR] Update GreyNoise Analyzer to support Community API

### ISSUE THREAD

**Issue by bradchiappetta** [TheHive-Project/Cortex-Analyzers#969]
**Feature description**
A clear and concise description of your feature request.
GreyNoise has released a new, free community API.  Suggest incorporating it to allow for broader usage.

**Describe the solution you'd like**
Allow GreyNoise analyzer to support both Community and Paid APIs.

**Additional context**
https://developer.greynoise.io/reference/community-api

**Comment by nadouani** [comment]
Closing as the PR has been merged
