### ISSUE TITLE
Update Cyberprotect Analyzer

### ISSUE THREAD

**Issue by ArthurCauchy** [TheHive-Project/Cortex-Analyzers#973]
**Feature description**
We just released Threatscore version 3. It is using a new API endpoint, a new subdomain, as well as a new data schema. We also updated the template for thehive and the preview PNG in assets.

**Bugfix**
The PR also fix inverted Cyberprotect and CyberCrime-Tracker README.md files.

**Comment by nadouani** [comment]
Closing as the PR has been aceepted
