### ISSUE TITLE
[Bug][EMLParser] incomplete headers

### ISSUE THREAD

**Issue by nicodeff** [TheHive-Project/Cortex-Analyzers#976]
Hello,

For few eml, the analyzer EMLParser display incomplete headers.
The headers interrupt in the "DKIM-Signature" part.

Last Line of headers part in the analyzer :
![image](https://user-images.githubusercontent.com/3795515/114386468-8c385f80-9b91-11eb-9c6d-c178193ed9db.png)

Headers : 
![image](https://user-images.githubusercontent.com/3795515/114385476-5fd01380-9b90-11eb-8ed9-d40201cfd7cf.png)

**Work environment**
 - Client OS: Windows
- Server OS: CentOS
 - Browse type and version: Chrome 89
- Cortex version: 3.1.1-1
 - Cortex Analyzer/Responder name: EMLParser
- Cortex Analyzer/Responder version: Last Version

Regards,

**Comment by nicodeff** [comment]
Hello, I have Additional Information.

For all eml with partial informations, the displayed headers stop to field "h=" in "DKIM-Signature".

Regards,

**Comment by nicodeff** [comment]
Hello,

Do, you have informations about this bug ?

Thanks,

Regards,

**Comment by ch0wm3in** [comment]
This pull request fixes it https://github.com/TheHive-Project/Cortex-Analyzers/pull/962
For some reason at some point someone introduced a 'content-type:' split into the EMLparser analyser on the header extractions even though it only extracts the headers and nothing else, at the very least even tough its unnecessary it should be an .rindex to the get the last index of 'content-type:' 

I made the pull request a while ago, but noone wants to merge it :(

**Comment by jeromeleonard** [comment]
a new version of the analyzer is coming. It has been almost completely rewritten and should fix this issue.

**Comment by nicodeff** [comment]
Hello @jeromeleonard.

I just tried to update all analyzer ans Responder Cortex via this method :

```
cd path/to/Cortex-Analyzers
git pull
for I in analyzers/*/requirements.txt; do sudo -H pip3 install -U -r $I || true; done
for I in responders/*/requirements.txt; do sudo -H pip3 install -U -r $I || true; done
```

After reload in cortex EmlParser 2.0, I have this error message : 
![image](https://user-images.githubusercontent.com/3795515/129583443-4192a2c9-28dc-4905-add4-f59f849173be.png)

Do you have any idea for resolve this problem ?

The python package eml_parser is already at the latest version.

Thanks,

Regards,

Nicolas Deffrenne

**Comment by nicodeff** [comment]
Hello,

On this git it is indicated to update Python.
https://github.com/GOVCERT-LU/eml_parser/issues/53

So I switched to version 3.9.6 and my problem has been solved.
Thank you so much,

By the way, this new version of the EmlParser analyzer is great 😃 
Thanks @jeromeleonard 

Regards,

Nicolas
