### ISSUE TITLE
[FR] Improve MISP analyzer results

### ISSUE THREAD

**Issue by dadokkio** [TheHive-Project/Cortex-Analyzers#984]
With multiple misp instances configurated and a lot of related events the template for MISP analyzer could be difficult to read

![old](https://user-images.githubusercontent.com/355183/117121353-c235c180-ad94-11eb-8697-c5a5ac83f00f.png)

We changed the template a bit to have separated instance as a tab and each result expandable, like this:

![new](https://user-images.githubusercontent.com/355183/117121513-fa3d0480-ad94-11eb-8e99-71ee321b548d.png)

If this could be useful I'm going to make a pull request. Any feedback?

**Comment by nadouani** [comment]
This update is useful, please feel free to make a PR for it and include it in 3.0.0
